import { useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { ChromeBlob } from '../components/ui/ChromeBlob'
import { AssetSlot } from '../components/ui/AssetSlot'
import { AnimatedCounter } from '../components/ui/AnimatedCounter'
import { useScrollReveal } from '../hooks/useScrollReveal'
import { useShockwave } from '../hooks/useShockwave'

gsap.registerPlugin(ScrollTrigger)

const stats = [
  '400% -- DEEPFAKE ATTACKS UP YoY',
  '✦',
  '70% -- IoT DEVICES HAVE CRITICAL VULNS',
  '✦',
  '$4.45M -- AVERAGE DATA BREACH COST 2024',
  '✦',
  '1 IN 5 MINUTES -- NEW DEEPFAKE CREATED GLOBALLY',
  '✦',
  '85% -- OF ONLINE CONTENT WILL BE AI-GENERATED BY 2026',
  '✦',
]

const reviews = [
  {
    text: 'I uploaded a video of my CEO that turned out to be completely AI-generated. DOBERMAN caught it in 3 seconds.',
    author: 'Marcus T.',
    role: 'IT Security Lead, London',
    badge: '98% FAKE',
    badgeColor: 'var(--danger)',
    rotate: -1.5,
  },
  {
    text: 'My home network had 4 critical vulnerabilities I had no idea about. Patched all of them in one afternoon.',
    author: 'Priya K.',
    role: 'Remote Software Engineer',
    badge: 'RISK: 74',
    badgeColor: 'var(--warning)',
    rotate: 1.5,
  },
  {
    text: 'The news verification alone is worth it. I paste every headline before sharing anything now. Saved me embarrassment twice.',
    author: 'David O.',
    role: 'Independent Journalist',
    badge: '3 FALSE FLAGS',
    badgeColor: 'var(--danger)',
    rotate: -1,
  },
  {
    text: 'BRAIN explained a zero-day exploit to me like a human being. Not like reading a CVE database. Actually useful.',
    author: 'Aisha M.',
    role: 'Cybersecurity Student',
    badge: 'BRAIN 5/5',
    badgeColor: 'var(--safe)',
    rotate: 1,
  },
  {
    text: 'Right-clicked a suspicious LinkedIn profile picture on my phone. DOBERMAN said 97% fake. Blocked immediately.',
    author: 'Tom R.',
    role: 'Senior Recruiter',
    badge: '97% FAKE',
    badgeColor: 'var(--danger)',
    rotate: -1.5,
  },
  {
    text: 'Scanned my entire smart home. Bulbs, TV, cameras, router. Got a full risk report with actual numbered steps.',
    author: 'Yuki N.',
    role: 'Smart Home Enthusiast',
    badge: '6 VULNS FOUND',
    badgeColor: 'var(--warning)',
    rotate: 1.5,
  },
]

const hPanels = [
  { num: '01', module: 'EYES', headline: 'See\nthrough\nthe fake.', sub: 'Upload any media. Get a trust score in seconds.' },
  { num: '02', module: 'NOSE', headline: 'Sniff out\nevery\nthreat.', sub: 'Your network has secrets. DOBERMAN finds them.' },
  { num: '03', module: 'BRAIN', headline: 'Ask\nanything.\nKnow it all.', sub: 'A security analyst available every second of every day.' },
  { num: '04', module: 'NEWS', headline: 'Real or\nfake?\nKnow now.', sub: 'Verify any headline or article in seconds.' },
  { num: '05', module: 'EXTENSION', headline: 'Works\neverywhere\nyou do.', sub: 'Right-click any image on the web. Get results instantly.' },
]

export default function Landing() {
  const navigate = useNavigate()
  const shockwave = useShockwave()
  const hContainerRef = useRef<HTMLDivElement>(null)

  const modulesHeaderRef = useScrollReveal()
  const newsHeaderRef = useScrollReveal()
  const extensionHeaderRef = useScrollReveal()
  const ctaCardRef = useScrollReveal({ y: 40, scale: 0.92 })

  useEffect(() => {
    const ctx = gsap.context(() => {
      const panels = gsap.utils.toArray<HTMLElement>('.h-panel')
      if (!panels.length) return
      gsap.to(panels, {
        xPercent: -100 * (panels.length - 1),
        ease: 'none',
        scrollTrigger: {
          trigger: '.h-container',
          pin: true,
          scrub: 1.2,
          snap: { snapTo: 1 / (panels.length - 1), duration: 0.5, ease: 'power2.inOut' },
          end: () => '+=' + panels.length * window.innerWidth,
        },
      })
    }, hContainerRef)
    return () => ctx.revert()
  }, [])

  return (
    <div style={{ background: 'var(--void)', minHeight: '100vh', overflowX: 'hidden' }}>

      {/* NAV */}
      <nav
        className="glass"
        style={{
          position: 'fixed',
          top: 16,
          left: '50%',
          transform: 'translateX(-50%)',
          width: 'calc(100% - 48px)',
          maxWidth: 1200,
          padding: '12px 24px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          zIndex: 200,
          borderRadius: 14,
        }}
      >
        <span style={{ fontFamily: 'Bebas Neue', fontSize: 22, letterSpacing: '0.2em' }}>
          DOBERMAN
        </span>
        <div style={{ display: 'flex', gap: 40, fontFamily: 'JetBrains Mono', fontSize: 12, color: 'var(--text-2)' }}>
          <a href="#modules" style={{ color: 'inherit', textDecoration: 'none' }}>MODULES</a>
          <a href="#news" style={{ color: 'inherit', textDecoration: 'none' }}>NEWS</a>
          <a href="#extension" style={{ color: 'inherit', textDecoration: 'none' }}>EXTENSION</a>
          <a href="#reviews" style={{ color: 'inherit', textDecoration: 'none' }}>REVIEWS</a>
        </div>
        <div style={{ display: 'flex', gap: 12 }}>
          <motion.button
            className="glass"
            whileHover={{ scale: 1.03 }}
            onClick={() => navigate('/auth')}
            style={{ padding: '8px 20px', fontSize: 13, fontFamily: 'Syne', fontWeight: 600, color: 'white', border: 'none', borderRadius: 8 }}
          >
            Sign In
          </motion.button>
          <motion.button
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={() => navigate('/auth')}
            style={{ padding: '8px 20px', background: 'white', color: 'black', fontSize: 13, fontFamily: 'Syne', fontWeight: 700, border: 'none', borderRadius: 8 }}
          >
            Get Started Free
          </motion.button>
        </div>
      </nav>

      {/* HERO */}
      <section style={{ minHeight: '100vh', position: 'relative', overflow: 'hidden', display: 'flex', alignItems: 'center' }}>
        <ChromeBlob size={700} speed={0.5} distort={0.45} style={{ top: '-120px', right: '-180px', opacity: 0.65, zIndex: 0 }} />
        <ChromeBlob size={280} speed={1.1} distort={0.65} style={{ bottom: '5%', left: '-60px', opacity: 0.3, zIndex: 0 }} />
        <ChromeBlob size={160} speed={0.7} distort={0.8} style={{ top: '40%', left: '35%', opacity: 0.15, zIndex: 0 }} />

        <div style={{ position: 'relative', zIndex: 1, padding: '120px 48px 80px', maxWidth: 1200, margin: '0 auto', width: '100%' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 60, alignItems: 'center' }}>
            <div>
              <motion.p
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.2, duration: 0.6 }}
                style={{ fontFamily: 'JetBrains Mono', fontSize: 11, letterSpacing: '0.2em', color: 'var(--chrome-dim)', marginBottom: 32, textTransform: 'uppercase' }}
              >
                [ CYBERSECURITY INTELLIGENCE -- 2026 ]
              </motion.p>

              {['THE', 'WATCH-', 'DOG.'].map((word, i) => (
                <motion.div
                  key={word}
                  initial={{ opacity: 0, y: 100, rotateX: 30 }}
                  animate={{ opacity: 1, y: 0, rotateX: 0 }}
                  transition={{ delay: 0.3 + i * 0.14, duration: 1.0, ease: [0.25, 0.1, 0.25, 1] }}
                  style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 'clamp(72px, 13vw, 160px)', lineHeight: 0.88, display: 'block', color: 'var(--chrome-white)' }}
                >
                  {word}
                </motion.div>
              ))}

              <motion.p
                initial={{ opacity: 0, y: 24 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.85, duration: 0.7 }}
                style={{ fontFamily: 'Syne', fontSize: 17, color: 'var(--text-2)', maxWidth: 460, marginTop: 40, lineHeight: 1.65 }}
              >
                Detect deepfakes. Expose IoT vulnerabilities.
                Verify news. Get expert cybersecurity advice.
                Three modules. One platform. Zero guesswork.
              </motion.p>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1.05, duration: 0.6 }}
                style={{ display: 'flex', gap: 14, marginTop: 48, flexWrap: 'wrap' }}
              >
                <motion.button
                  whileHover={{ scale: 1.04, boxShadow: '0 0 40px rgba(255,255,255,0.15)' }}
                  whileTap={{ scale: 0.97 }}
                  onClick={(e) => { shockwave(e); navigate('/auth') }}
                  style={{ padding: '16px 44px', background: 'white', color: 'black', fontFamily: 'Syne', fontWeight: 700, fontSize: 15, border: 'none', borderRadius: 12 }}
                >
                  Deploy Free
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.04 }}
                  className="glass"
                  onClick={() => navigate('/auth')}
                  style={{ padding: '16px 44px', fontFamily: 'Syne', fontWeight: 600, fontSize: 15, color: 'white', border: '1px solid var(--glass-border)', borderRadius: 12, background: 'transparent' }}
                >
                  See It Work
                </motion.button>
              </motion.div>

              <motion.p
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 1.3 }}
                style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)', marginTop: 20 }}
              >
                Free tier -- no credit card required
              </motion.p>
            </div>

            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.5, duration: 1.0 }}
            >
              <AssetSlot
                id="slot-hero-3d"
                label="HERO 3D ASSET"
                description="Spline doberman / chrome sphere / shield orb -- 600x700px"
                type="spline"
                height={600}
                style={{ borderRadius: 24 }}
              />
            </motion.div>
          </div>
        </div>

        <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: 200, background: 'linear-gradient(to bottom, transparent, var(--void))', pointerEvents: 'none', zIndex: 2 }} />
      </section>

      {/* STATS TICKER */}
      <div style={{ overflow: 'hidden', borderTop: '1px solid var(--glass-border)', borderBottom: '1px solid var(--glass-border)', padding: '14px 0', background: 'var(--void-1)' }}>
        <div style={{ display: 'flex', animation: 'ticker-scroll 35s linear infinite', width: 'max-content' }}>
          {[...stats, ...stats].map((s, i) => (
            <span key={i} style={{ fontFamily: 'JetBrains Mono', fontSize: 12, letterSpacing: '0.12em', color: 'var(--chrome-dim)', paddingRight: 48, whiteSpace: 'nowrap', textTransform: 'uppercase' }}>
              {s}
            </span>
          ))}
        </div>
      </div>

      {/* MODULES */}
      <section id="modules" style={{ padding: '120px 48px', maxWidth: 1200, margin: '0 auto' }}>
        <div ref={modulesHeaderRef} style={{ textAlign: 'center', marginBottom: 80 }}>
          <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, letterSpacing: '0.2em', color: 'var(--chrome-dim)', marginBottom: 20 }}>
            [ THREE MODULES. ONE WATCHDOG. ]
          </p>
          <h2 style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92 }}>
            Intelligence built<br />for today's threats.
          </h2>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 24 }}>
          {/* EYES */}
          <motion.div
            className="glass"
            initial={{ opacity: 0, x: -120, rotate: -4 }}
            whileInView={{ opacity: 1, x: 0, rotate: 0 }}
            transition={{ duration: 0.85, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true, margin: '-60px' }}
            whileHover={{ y: -8, transition: { duration: 0.2 } }}
            style={{ padding: 36, borderRadius: 24, position: 'relative', overflow: 'hidden' }}
          >
            <AssetSlot id="slot-eyes-3d" label="EYES 3D ASSET" description="Spline rotating eyeball -- 300x260px" type="spline" height={260} style={{ marginBottom: 28 }} />
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.2em', color: 'var(--chrome-dim)', marginBottom: 12 }}>01 -- DEEPFAKE DETECTION</p>
            <h3 style={{ fontFamily: 'Bebas Neue', fontSize: 56, letterSpacing: '0.1em', marginBottom: 16 }}>EYES</h3>
            <p style={{ color: 'var(--text-2)', fontSize: 15, lineHeight: 1.65, marginBottom: 24 }}>
              Upload any image, video, or audio. DOBERMAN's detection engine analyzes it
              against known deepfake signatures and returns a trust score in seconds.
            </p>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)' }}>Hive AI - XceptionNet - EfficientNet - MesoNet</p>
            <ChromeBlob size={200} speed={0.2} distort={0.5} style={{ bottom: -80, right: -80, opacity: 0.04, pointerEvents: 'none' }} />
          </motion.div>

          {/* NOSE */}
          <motion.div
            className="glass"
            initial={{ opacity: 0, y: 100, scale: 0.93 }}
            whileInView={{ opacity: 1, y: 0, scale: 1 }}
            transition={{ duration: 0.85, delay: 0.15, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true, margin: '-60px' }}
            whileHover={{ y: -8, transition: { duration: 0.2 } }}
            style={{ padding: 36, borderRadius: 24, position: 'relative', overflow: 'hidden' }}
          >
            <AssetSlot id="slot-nose-3d" label="NOSE 3D ASSET" description="Spline radar / network nodes -- 300x260px" type="spline" height={260} style={{ marginBottom: 28 }} />
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.2em', color: 'var(--chrome-dim)', marginBottom: 12 }}>02 -- NETWORK INTELLIGENCE</p>
            <h3 style={{ fontFamily: 'Bebas Neue', fontSize: 56, letterSpacing: '0.1em', marginBottom: 16 }}>NOSE</h3>
            <p style={{ color: 'var(--text-2)', fontSize: 15, lineHeight: 1.65, marginBottom: 24 }}>
              Describe your network environment. DOBERMAN identifies device vulnerabilities,
              maps real CVEs, and gives you a prioritized action plan.
            </p>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)' }}>NIST NVD - Real CVE Mapping - Device Fingerprinting</p>
            <ChromeBlob size={200} speed={0.2} distort={0.5} style={{ bottom: -80, right: -80, opacity: 0.04, pointerEvents: 'none' }} />
          </motion.div>

          {/* BRAIN */}
          <motion.div
            className="glass"
            initial={{ opacity: 0, x: 120, rotate: 4 }}
            whileInView={{ opacity: 1, x: 0, rotate: 0 }}
            transition={{ duration: 0.85, delay: 0.3, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true, margin: '-60px' }}
            whileHover={{ y: -8, transition: { duration: 0.2 } }}
            style={{ padding: 36, borderRadius: 24, position: 'relative', overflow: 'hidden' }}
          >
            <AssetSlot id="slot-brain-3d" label="BRAIN 3D ASSET" description="Spline neural mesh / glowing brain -- 300x260px" type="spline" height={260} style={{ marginBottom: 28 }} />
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.2em', color: 'var(--chrome-dim)', marginBottom: 12 }}>03 -- AI SECURITY ANALYST</p>
            <h3 style={{ fontFamily: 'Bebas Neue', fontSize: 56, letterSpacing: '0.1em', marginBottom: 16 }}>BRAIN</h3>
            <p style={{ color: 'var(--text-2)', fontSize: 15, lineHeight: 1.65, marginBottom: 24 }}>
              Ask anything. Upload suspicious files. DOBERMAN explains threats in plain language
              and gives you a concrete next step. Like having a security analyst on call 24/7.
            </p>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)' }}>Claude Sonnet - Context-aware - File Upload Support</p>
            <ChromeBlob size={200} speed={0.2} distort={0.5} style={{ bottom: -80, right: -80, opacity: 0.04, pointerEvents: 'none' }} />
          </motion.div>
        </div>
      </section>

      {/* STATS ROW */}
      <div style={{ padding: '80px 48px', background: 'var(--void-1)', borderTop: '1px solid var(--glass-border)', borderBottom: '1px solid var(--glass-border)' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 40, textAlign: 'center' }}>
          {[
            { target: 400, suffix: '%', label: 'Rise in deepfake attacks' },
            { target: 70, suffix: '%', label: 'IoT devices with critical vulns' },
            { target: 4, suffix: 'M+', prefix: '$', label: 'Average breach cost' },
            { target: 3, suffix: ' modules', label: 'One platform' },
          ].map((stat, i) => (
            <div key={i}>
              <div style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 'clamp(40px, 5vw, 64px)', lineHeight: 1, marginBottom: 8 }}>
                <AnimatedCounter target={stat.target} prefix={stat.prefix} suffix={stat.suffix} />
              </div>
              <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)', letterSpacing: '0.1em' }}>
                {stat.label.toUpperCase()}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* HORIZONTAL PINNED SCROLL */}
      <div ref={hContainerRef} className="h-container" style={{ overflow: 'hidden' }}>
        <div style={{ display: 'flex', width: `${hPanels.length * 100}vw`, height: '100vh' }}>
          {hPanels.map((panel, i) => (
            <div
              key={i}
              className="h-panel"
              style={{
                width: '100vw',
                height: '100vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                position: 'relative',
                overflow: 'hidden',
                background: i % 2 === 0 ? 'var(--void)' : 'var(--void-1)',
              }}
            >
              <ChromeBlob size={600} speed={0.3} distort={0.5}
                style={{ opacity: 0.2, top: '50%', left: '50%', transform: 'translate(-50%, -50%)' }} />
              <div
                className="glass"
                style={{ position: 'relative', zIndex: 1, padding: '60px 72px', borderRadius: 32, maxWidth: 600, textAlign: 'center' }}
              >
                <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, letterSpacing: '0.25em', color: 'var(--chrome-dim)', marginBottom: 20 }}>
                  {panel.num} -- {panel.module}
                </p>
                <h2 style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 'clamp(48px, 8vw, 96px)', lineHeight: 0.9, whiteSpace: 'pre-line', marginBottom: 32 }}>
                  {panel.headline}
                </h2>
                <p style={{ fontFamily: 'Syne', fontSize: 18, color: 'var(--text-2)', lineHeight: 1.6 }}>
                  {panel.sub}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* BLOB DIVIDER */}
      <div style={{ position: 'relative', height: 280, overflow: 'hidden', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <ChromeBlob size={480} speed={0.35} distort={0.55} style={{ opacity: 0.45 }} />
        <span style={{ position: 'absolute', zIndex: 2, fontFamily: 'Bebas Neue', fontSize: 'clamp(60px, 12vw, 140px)', letterSpacing: '0.25em', color: 'rgba(255,255,255,0.04)', pointerEvents: 'none', userSelect: 'none' }}>
          DOBERMAN
        </span>
      </div>

      {/* NEWS SECTION */}
      <section id="news" style={{ padding: '120px 48px', maxWidth: 1200, margin: '0 auto' }}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 80, alignItems: 'center' }}>
          <div ref={newsHeaderRef}>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, letterSpacing: '0.2em', color: 'var(--danger)', marginBottom: 20 }}>
              [ FAKE NEWS DETECTION ]
            </p>
            <h2 style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92, marginBottom: 20 }}>
              Don't believe<br />everything<br />you read.
            </h2>
            <p style={{ color: 'var(--text-2)', fontSize: 16, maxWidth: 500, lineHeight: 1.65, marginBottom: 36 }}>
              Paste any headline, claim, or article URL. DOBERMAN cross-references it,
              checks source quality, and gives you a credibility verdict in seconds.
            </p>
            <motion.button
              whileHover={{ scale: 1.04 }}
              whileTap={{ scale: 0.97 }}
              onClick={() => navigate('/auth')}
              style={{ padding: '14px 36px', background: 'white', color: 'black', fontFamily: 'Syne', fontWeight: 700, fontSize: 14, border: 'none', borderRadius: 10 }}
            >
              Try News Verification
            </motion.button>
          </div>
          <AssetSlot id="slot-news-photo" label="NEWS SECTION PHOTO" description="Newspaper or phone with news app -- 600x500px" type="image" height={400} />
        </div>
      </section>

      {/* EXTENSION SECTION */}
      <section id="extension" style={{ padding: '120px 48px', background: 'var(--void-1)', borderTop: '1px solid var(--glass-border)' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 80, alignItems: 'center', marginBottom: 60 }}>
            <div ref={extensionHeaderRef}>
              <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, letterSpacing: '0.2em', color: 'var(--chrome-dim)', marginBottom: 20 }}>
                [ BROWSER EXTENSION ]
              </p>
              <h2 style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92, marginBottom: 20 }}>
                DOBERMAN<br />everywhere<br />you browse.
              </h2>
              <p style={{ color: 'var(--text-2)', fontSize: 16, maxWidth: 500, lineHeight: 1.65, marginBottom: 36 }}>
                Right-click any image, video, or selected text on any website.
                DOBERMAN analyzes it instantly and shows you the result in a
                floating panel - without ever leaving the page.
              </p>
              <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 36 }}>
                {['Right-click any image', 'Selected text verification', 'Works on all sites'].map((feat) => (
                  <span key={feat} className="glass" style={{ padding: '8px 16px', borderRadius: 8, fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-2)' }}>
                    {feat}
                  </span>
                ))}
              </div>
              <motion.button
                whileHover={{ scale: 1.04, boxShadow: '0 0 30px rgba(255,255,255,0.1)' }}
                style={{ padding: '14px 36px', background: 'white', color: 'black', fontFamily: 'Syne', fontWeight: 700, fontSize: 14, border: 'none', borderRadius: 10 }}
              >
                Add to Chrome -- Free
              </motion.button>
            </div>
            <AssetSlot id="slot-extension-demo" label="EXTENSION DEMO VIDEO" description="Screen recording -- right-click image, see overlay -- 800x500px MP4" type="video" height={460} />
          </div>
        </div>
      </section>

      {/* BLOB DIVIDER 2 */}
      <div style={{ position: 'relative', height: 280, overflow: 'hidden', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <ChromeBlob size={520} speed={0.28} distort={0.6} style={{ opacity: 0.4 }} />
        <span style={{ position: 'absolute', zIndex: 2, fontFamily: 'Bebas Neue', fontSize: 'clamp(60px, 12vw, 140px)', letterSpacing: '0.25em', color: 'rgba(255,255,255,0.03)', pointerEvents: 'none', userSelect: 'none' }}>
          SECURITY
        </span>
      </div>

      {/* REVIEWS */}
      <section id="reviews" style={{ padding: '120px 0 120px 48px', overflow: 'hidden' }}>
        <div style={{ maxWidth: 1200, marginBottom: 60 }}>
          <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, letterSpacing: '0.2em', color: 'var(--chrome-dim)', marginBottom: 20 }}>
            [ WHAT USERS SAY ]
          </p>
          <h2 style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92 }}>
            The dog<br />delivers.
          </h2>
        </div>

        <motion.div
          drag="x"
          dragConstraints={{ right: 0, left: -(reviews.length * 380) }}
          style={{ display: 'flex', gap: 20, width: 'max-content' }}
        >
          {reviews.map((r, i) => (
            <motion.div
              key={i}
              className="glass"
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              whileHover={{ y: -8, rotate: 0, transition: { duration: 0.2 } }}
              style={{ width: 360, padding: 32, borderRadius: 20, flexShrink: 0, position: 'relative', overflow: 'hidden', rotate: r.rotate }}
            >
              <span style={{
                position: 'absolute', top: 20, right: 20,
                fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.15em',
                color: r.badgeColor,
                background: `${r.badgeColor}22`,
                border: `1px solid ${r.badgeColor}44`,
                padding: '3px 8px', borderRadius: 4,
              }}>
                {r.badge}
              </span>
              <p style={{ fontFamily: 'Syne', fontSize: 15, color: 'var(--text-2)', lineHeight: 1.65, marginBottom: 24, marginTop: 8 }}>
                "{r.text}"
              </p>
              <div>
                <p style={{ fontFamily: 'Syne', fontWeight: 700, fontSize: 14, color: 'var(--text-1)' }}>{r.author}</p>
                <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)', marginTop: 4 }}>{r.role}</p>
              </div>
              <ChromeBlob size={120} speed={0.15} distort={0.4} style={{ bottom: -40, right: -40, opacity: 0.05 }} />
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* FINAL CTA */}
      <section style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' }}>
        <ChromeBlob size={800} speed={0.25} distort={0.55} style={{ opacity: 0.35 }} />
        <div ref={ctaCardRef} style={{ position: 'relative', zIndex: 1 }}>
          <div className="glass" style={{ padding: '90px 72px', borderRadius: 36, textAlign: 'center', maxWidth: 720 }}>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, letterSpacing: '0.2em', color: 'var(--chrome-dim)', marginBottom: 28 }}>
              THE WATCHDOG IS READY
            </p>
            <h2 style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: 'clamp(52px, 9vw, 110px)', lineHeight: 0.88, marginBottom: 36 }}>
              Deploy<br />DOBERMAN.
            </h2>
            <p style={{ fontFamily: 'Syne', fontSize: 17, color: 'var(--text-2)', marginBottom: 52 }}>
              Free tier. No credit card. No limits on intelligence.
            </p>
            <motion.button
              whileHover={{ scale: 1.05, boxShadow: '0 0 60px rgba(255,255,255,0.2)' }}
              whileTap={{ scale: 0.96 }}
              onClick={(e) => { shockwave(e); navigate('/auth') }}
              style={{ padding: '20px 72px', background: 'white', color: 'black', fontFamily: 'Syne', fontWeight: 700, fontSize: 17, border: 'none', borderRadius: 14 }}
            >
              Get Started Free
            </motion.button>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)', marginTop: 20 }}>
              3 free scans per module per day -- no card required
            </p>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer style={{ borderTop: '1px solid var(--glass-border)', padding: '32px 48px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--void-1)', flexWrap: 'wrap', gap: 20 }}>
        <span style={{ fontFamily: 'Bebas Neue', fontSize: 18, letterSpacing: '0.2em' }}>DOBERMAN</span>
        <div style={{ display: 'flex', gap: 32, fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)' }}>
          <a href="/privacy" style={{ color: 'inherit', textDecoration: 'none' }}>Privacy</a>
          <a href="/terms" style={{ color: 'inherit', textDecoration: 'none' }}>Terms</a>
          <a href="mailto:hello@doberman.ai" style={{ color: 'inherit', textDecoration: 'none' }}>Contact</a>
        </div>
        <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'var(--text-3)' }}>
          2026 DOBERMAN. All rights reserved.
        </p>
      </footer>
    </div>
  )
}
