import { useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { useShockwave } from '../hooks/useShockwave'
import { AnimatedCounter } from '../components/ui/AnimatedCounter'
import { VideoBlob } from '../components/ui/VideoBlob'
import { ThemeToggle } from '../components/ui/ThemeToggle'

gsap.registerPlugin(ScrollTrigger)

const stats = [
  '400% -- DEEPFAKE ATTACKS UP YoY',
  '✦',
  '70% -- IoT DEVICES HAVE CRITICAL VULNS',
  '✦',
  '$4.45M -- AVERAGE DATA BREACH COST 2024',
  '✦',
  '1 IN 5 MINUTES -- NEW DEEPFAKE CREATED GLOBALLY',
  '✦',
  '85% -- OF ONLINE CONTENT WILL BE AI-GENERATED BY 2026',
  '✦',
]

const reviews = [
  { text: 'I uploaded a video of my CEO that turned out to be completely AI-generated. D0B3RMAN caught it in 3 seconds.', author: 'Honour J.D', role: 'Cyber Sec Student', badge: '98% FAKE', badgeColor: 'var(--danger)', rotate: -1.5 },
  { text: 'My home network had 4 critical vulnerabilities I had no idea about. Patched all of them in one afternoon.', author: 'Perez E', role: 'Cyber Sec Student', badge: 'RISK: 74', badgeColor: 'var(--warning)', rotate: 1.5 },
  { text: 'The news verification alone is worth it. I paste every headline before sharing anything now.', author: 'Issac J', role: 'Computer Science Student', badge: '3 FALSE FLAGS', badgeColor: 'var(--danger)', rotate: -1 },
  { text: 'D0B3RMAN Intelligence explained a zero-day exploit to me like a human being. Not like reading a CVE database. Actually useful.', author: 'Dave 101', role: 'Software Engineer', badge: 'D0B3RMAN I. 5/5', badgeColor: 'var(--safe)', rotate: 1 },
  { text: 'Right-clicked a suspicious LinkedIn profile picture. D0B3RMAN said 97% fake. Blocked immediately.', author: 'Baddejo I', role: 'Vice President, PCU', badge: '97% FAKE', badgeColor: 'var(--danger)', rotate: -1.5 },
  { text: 'Scanned my entire smart home. Bulbs, TV, cameras, router. Got a full risk report with numbered steps.', author: 'Mr Olusanu', role: 'My Dad', badge: '6 VULNS FOUND', badgeColor: 'var(--warning)', rotate: 1.5 },
]

const hPanels = [
  { num: '01', module: 'DEEP FAKE INTELLIGENCE', headline: 'See\nthrough\nthe fake.', sub: 'Upload any media. Get a trust score in seconds.' },
  { num: '02', module: 'D0B3RMAN INTELLIGENCE', headline: 'Ask\nanything.\nKnow it all.', sub: 'A security analyst available every second of every day.' },
  { num: '03', module: 'NEWS', headline: 'Real or\nfake?\nKnow now.', sub: 'Verify any headline or article in seconds.' },
  { num: '04', module: 'EXTENSION', headline: 'Works\neverywhere\nyou do.', sub: 'Right-click any image on the web. Get results instantly.' },
]

const IN_VIEW = {
  initial: { opacity: 0, y: 48 },
  whileInView: { opacity: 1, y: 0 },
  transition: { duration: 0.8, ease: [0.25, 0.1, 0.25, 1] as const },
  viewport: { once: true, margin: '-60px' },
}

export default function Landing() {
  const navigate = useNavigate()
  const shockwave = useShockwave()
  const hContainerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.utils.toArray<HTMLElement>('.gsap-heading').forEach((el) => {
        gsap.fromTo(
          el,
          { opacity: 0, y: 60 },
          {
            opacity: 1,
            y: 0,
            duration: 0.9,
            ease: 'power3.out',
            scrollTrigger: {
              trigger: el,
              start: 'top 85%',
              toggleActions: 'play none none none',
            },
          }
        )
      })

      const container = hContainerRef.current
      const panels = container ? Array.from(container.querySelectorAll<HTMLElement>('.h-panel')) : []
      if (panels.length > 1) {
        gsap.to(panels, {
          xPercent: -100 * (panels.length - 1),
          ease: 'none',
          scrollTrigger: {
            trigger: container,
            pin: true,
            scrub: 1.2,
            snap: {
              snapTo: 1 / (panels.length - 1),
              duration: 0.6,
              ease: 'power2.inOut',
            },
            end: () => '+=' + panels.length * window.innerWidth,
          },
        })
      }
    })

    return () => ctx.revert()
  }, [])

  return (
    <div style={{ background: 'var(--void)', minHeight: '100vh', overflowX: 'hidden' }}>

      {/* ─── NAV ─────────────────────────────────────────── */}
      <nav style={{
        position: 'fixed', top: 12, left: '50%', transform: 'translateX(-50%)',
        width: 'calc(100% - 32px)', maxWidth: 1200,
        padding: '12px 24px',
        background: 'var(--nav-glass-bg)',
        backdropFilter: 'blur(40px)', WebkitBackdropFilter: 'blur(40px)',
        border: '1px solid var(--nav-glass-border)',
        borderRadius: 14,
        boxShadow: 'var(--nav-glass-shadow)',
        zIndex: 200,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        transition: 'background 0.25s var(--ease-apple), border-color 0.25s var(--ease-apple)',
      }}>
        <style>{`@media(max-width:768px){.nav-links,.nav-signin{display:none!important}}`}</style>
        {/* Nav pill background is now theme-aware glass (dark glass in dark mode, light frosted glass in light
            mode), so its text follows the matching --nav-text-* tokens instead of being fixed light. */}
        <span style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 22, letterSpacing: '0.2em', color: 'var(--nav-text-1)' }}>D0B3RMAN</span>
        <div className="nav-links" style={{ display: 'flex', gap: 40, fontFamily: 'Inter', fontSize: 12, color: 'var(--nav-text-2)' }}>
          <a href="#modules" style={{ color: 'inherit', textDecoration: 'none' }}>MODULES</a>
          <a href="#intelligence" style={{ color: 'inherit', textDecoration: 'none' }}>INTELLIGENCE</a>
          <a href="#news" style={{ color: 'inherit', textDecoration: 'none' }}>NEWS</a>
          <a href="#reviews" style={{ color: 'inherit', textDecoration: 'none' }}>REVIEWS</a>
        </div>
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <ThemeToggle size={14} />
          <motion.button
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={() => navigate('/auth')}
            className="nav-signin"
            style={{ padding: '8px 20px', background: 'var(--ovw-0p06)', backdropFilter: 'blur(20px)', border: '1px solid var(--ovw-0p12)', borderRadius: 8, color: 'var(--nav-text-3)', fontFamily: 'Inter', fontWeight: 600, fontSize: 13, boxShadow: 'inset 0 1px 0 var(--ovw-0p18)' }}>
            Sign In
          </motion.button>
          <motion.button
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={() => navigate('/auth')}
            style={{ padding: '8px 14px', background: 'var(--chrome-white)', color: 'var(--void)', fontFamily: 'Inter', fontWeight: 700, fontSize: 12, border: 'none', borderRadius: 8 }}>
            Get Started Free
          </motion.button>
        </div>
      </nav>

      {/* ─── HERO ────────────────────────────────────────── */}
      <section style={{ minHeight: '100vh', position: 'relative', overflow: 'hidden', background: 'var(--void)', display: 'flex', alignItems: 'center' }}>

        {/* Perspective room grid — shift vanishing point toward dog so it sits in the black void */}
        <img
          src="/assets/video/22ee8c4a4ffcfe6b8012f297b4232309.jpg"
          alt=""
          style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', objectPosition: '68% center', opacity: 0.6, pointerEvents: 'none', zIndex: 0 }}
        />
        {/* Deep vignette — keeps center black void dark, fades bright grid edges */}
        <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 55% 60% at 68% 50%, rgba(0,0,0,0) 0%, rgba(0,0,0,0.55) 60%, rgba(0,0,0,0.92) 100%)', pointerEvents: 'none', zIndex: 1 }} />
        {/* Subtle green bloom at vanishing point */}
        <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 30% 35% at 68% 50%, rgba(48,209,88,0.06) 0%, transparent 100%)', pointerEvents: 'none', zIndex: 1 }} />

        <motion.div
          className="hero-portrait"
          initial={{ opacity: 0 }} animate={{ opacity: 1 }}
          transition={{ delay: 0.25, duration: 1.4 }}
          style={{ position: 'absolute', right: 0, top: 0, bottom: 0, width: 'clamp(220px, 36%, 440px)', zIndex: 2, pointerEvents: 'none' }}
        >
          <img
            src="/assets/video/b78ad4f230a4015d24a420fce2a7d53b.jpg"
            alt=""
            onError={(e) => { const p = e.currentTarget.parentElement; if (p) p.style.display = 'none' }}
            style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 18%', display: 'block' }}
          />
          {/* Blend left edge into page; keep right/top transparent so grid lines show through */}
          <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to right, #000 0%, rgba(0,0,0,0.6) 30%, transparent 65%)' }} />
          <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: '30%', background: 'linear-gradient(to bottom, transparent, #000)' }} />
        </motion.div>

        <style>{`
          @media(max-width:768px){
            .hero-portrait{width:60%!important}
            .hero-portrait img{opacity:0.85}
          }
          @media(max-width:640px){
            .dfi-grid{grid-template-columns:1fr!important}
            .dfi-video{order:-1!important;height:160px!important}
          }
        `}</style>

        <div style={{ position: 'relative', zIndex: 3, padding: 'clamp(100px,15vw,120px) clamp(20px,5vw,48px) 80px', maxWidth: 1200, margin: '0 auto', width: '100%' }}>

          <motion.p
            initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.15, duration: 0.6 }}
            style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.05em', color: 'var(--ovw-0p25)', marginBottom: 36, textTransform: 'uppercase' }}>
            [ CYBERSECURITY INTELLIGENCE -- 2026 ]
          </motion.p>

          <div style={{ position: 'relative', marginBottom: 48 }}>
            <motion.div
              initial={{ opacity: 0, y: 80 }} animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.9, ease: [0.25, 0.1, 0.25, 1] }}
              style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(44px, 11vw, 145px)', lineHeight: 0.88, color: 'white', position: 'relative', zIndex: 1 }}>
              THE
            </motion.div>
            <motion.div
              initial={{ opacity: 0, y: 80 }} animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.35, duration: 0.9, ease: [0.25, 0.1, 0.25, 1] }}
              style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(44px, 11vw, 145px)', lineHeight: 0.88, color: 'white', position: 'relative', zIndex: 3 }}>
              WATCH-
            </motion.div>
            <motion.div
              initial={{ opacity: 0, y: 80 }} animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5, duration: 0.9, ease: [0.25, 0.1, 0.25, 1] }}
              style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(44px, 11vw, 145px)', lineHeight: 0.88, color: 'white', position: 'relative', zIndex: 1 }}>
              DOG.
            </motion.div>
          </div>

          <motion.p
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.8 }}
            style={{ fontFamily: 'Inter', fontSize: 17, color: 'rgba(255,255,255,0.75)', maxWidth: 460, lineHeight: 1.65, position: 'relative', zIndex: 4 }}>
            Detect deepfakes. Verify news.
            Get expert cybersecurity advice.
            Two modules. One platform. Zero guesswork.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.0 }}
            style={{ display: 'flex', gap: 16, marginTop: 40, flexWrap: 'wrap', position: 'relative', zIndex: 4 }}>
            {/* Hero CTAs sit on the permanently-dark hero backdrop in both themes (heavy vignette keeps it dark
                regardless of --void), so they're pinned to the same white/black values dark mode already
                resolved to — var(--chrome-white)/var(--void) used to invert to a near-black button in light
                mode, which vanished against the dark backdrop instead of reading as a solid white pill. */}
            <motion.button
              whileHover={{ scale: 1.04, boxShadow: '0 0 40px rgba(255,255,255,0.2)' }}
              whileTap={{ scale: 0.97 }}
              onClick={(e) => { shockwave(e); navigate('/auth') }}
              style={{ padding: '16px 44px', background: '#FFFFFF', color: '#0A0A0F', fontFamily: 'Inter', fontWeight: 700, fontSize: 15, border: 'none', borderRadius: 12 }}>
              Deploy Free
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.04 }}
              whileTap={{ scale: 0.97 }}
              onClick={() => navigate('/auth')}
              style={{ padding: '16px 44px', background: 'rgba(255,255,255,0.109)', backdropFilter: 'blur(20px)', WebkitBackdropFilter: 'blur(20px)', border: '1px solid rgba(255,255,255,0.272)', borderRadius: 12, color: 'white', fontFamily: 'Inter', fontWeight: 600, fontSize: 15, boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.526)' }}>
              See It Work
            </motion.button>
          </motion.div>

          <motion.p
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.3 }}
            style={{ fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p2)', marginTop: 20, position: 'relative', zIndex: 4 }}>
            Free tier -- no credit card required
          </motion.p>

          <p style={{ position: 'absolute', top: 120, right: 0, fontFamily: 'Inter', fontSize: 10, color: 'var(--ovw-0p1)', letterSpacing: '0.03em', writingMode: 'vertical-rl', zIndex: 5 }}>
            CYBERSECURITY -- EST. 2026
          </p>
          <p style={{ position: 'absolute', bottom: 40, right: 0, fontFamily: 'Inter', fontSize: 10, color: 'var(--ovw-0p1)', letterSpacing: '0.03em', zIndex: 5 }}>
            v1.0.0 -- D0B3RMAN.AI
          </p>
        </div>

        <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: 200, background: 'linear-gradient(to bottom, transparent, #000)', zIndex: 3, pointerEvents: 'none' }} />
      </section>

      {/* ─── STATS TICKER ────────────────────────────────── */}
      <div style={{ overflow: 'hidden', borderTop: '1px solid var(--ovw-0p06)', borderBottom: '1px solid var(--ovw-0p06)', padding: '14px 0', background: 'var(--void)' }}>
        <div style={{ display: 'flex', animation: 'ticker-scroll 35s linear infinite', width: 'max-content' }}>
          {[...stats, ...stats].map((s, i) => (
            <span key={i} style={{ fontFamily: 'Inter', fontSize: 12, letterSpacing: '0.04em', color: 'var(--ovw-0p25)', paddingRight: 48, whiteSpace: 'nowrap', textTransform: 'uppercase' }}>
              {s}
            </span>
          ))}
        </div>
      </div>

      {/* ─── MODULES ─────────────────────────────────────── */}
      <section id="modules" style={{ position: 'relative', overflow: 'hidden', padding: 'clamp(60px,10vw,120px) clamp(20px,4vw,48px)', background: 'var(--void)' }}>

        <div style={{ position: 'relative', zIndex: 1, maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 80 }}>
            <p style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.05em', color: 'var(--ovw-0p25)', marginBottom: 20 }}>
              [ TWO MODULES. ONE WATCHDOG. ]
            </p>
            <h2 className="gsap-heading" style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92 }}>
              Intelligence built<br />for today's threats.
            </h2>
          </div>

          {/* Deep Fake Intelligence card */}
          <motion.div
            className="glass"
            initial={{ opacity: 0, x: -80, rotate: -2 }}
            whileInView={{ opacity: 1, x: 0, rotate: 0 }}
            transition={{ duration: 0.85, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true, margin: '-60px' }}
            whileHover={{ y: -8, transition: { duration: 0.2 } }}
            style={{ padding: 36, borderRadius: 24, position: 'relative', overflow: 'hidden', marginBottom: 24 }}
          >
            <div className="dfi-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 36, alignItems: 'center' }}>
              <div>
                <p style={{ fontFamily: 'Inter', fontSize: 10, letterSpacing: '0.05em', color: 'var(--ovw-0p3)', marginBottom: 12 }}>01 -- DEEPFAKE DETECTION</p>
                <h3 style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 'clamp(40px, 6vw, 72px)', letterSpacing: '0.08em', marginBottom: 16, lineHeight: 0.95 }}>DEEP FAKE<br />INTELLIGENCE</h3>
                <p style={{ color: 'var(--ovw-0p5)', fontSize: 15, lineHeight: 1.65, marginBottom: 24 }}>
                  Upload any image, video, or audio. D0B3RMAN's detection engine analyzes it
                  against known deepfake signatures and returns a trust score in seconds.
                </p>
                <p style={{ fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p2)', marginBottom: 28 }}>Hive AI · XceptionNet · EfficientNet · MesoNet</p>
                <motion.button
                  whileHover={{ scale: 1.04 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={() => navigate('/auth')}
                  style={{ padding: '12px 32px', background: 'var(--chrome-white)', color: 'var(--void)', fontFamily: 'Inter', fontWeight: 700, fontSize: 14, border: 'none', borderRadius: 10, cursor: 'pointer' }}
                >
                  Try Deep Fake Detection
                </motion.button>
              </div>
              <div className="dfi-video" style={{ position: 'relative', height: 320, borderRadius: 16, overflow: 'hidden', background: '#060606' }}>
                <img
                  src="/assets/video/0a068fc3612b18fb193aa68da61d7bb3.jpg"
                  alt="Deepfake detection mesh overlay"
                  style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', display: 'block' }}
                />
                <div style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.1)', border: '1px solid var(--ovw-0p06)' }} />
                {/* Fixed scrim + fixed light text for the caption — the photo underneath isn't theme-adaptive, so a
                    theme-swapping text color risked landing invisible depending on the photo's own brightness. */}
                <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(0,0,0,0.65) 0%, transparent 30%)', zIndex: 1 }} />
                <div style={{ position: 'absolute', bottom: 14, left: 16, fontFamily: 'Inter', fontSize: 9, letterSpacing: '0.05em', color: 'rgba(255,255,255,0.85)', zIndex: 2 }}>
                  DEEP FAKE INTELLIGENCE -- DEEPFAKE DETECTION
                </div>
              </div>
            </div>
          </motion.div>

          {/* D0B3RMAN Intelligence — no card wrapper: the video is the only thing that needs a dark surface (its
              own black background, contained in a squircle), so the heading/copy/button sit directly on the
              section's normal page background and use the same theme-adaptive tokens as every other module,
              instead of being dragged into a fixed dark "feature card" that only worked in dark mode. */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, delay: 0.15, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true, margin: '-60px' }}
          >
            <style>{`@media(max-width:480px){.daye-landing-circle{width:176px!important;height:176px!important}}`}</style>
            <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 24 }}>
              <div className="daye-landing-circle" style={{ position: 'relative', width: 240, height: 240, borderRadius: '50%', overflow: 'hidden', border: '2px solid rgba(48,209,88,0.35)', boxShadow: '0 0 44px rgba(48,209,88,0.16)', background: '#000' }}>
                <video
                  autoPlay muted loop playsInline preload="auto"
                  style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }}
                >
                  <source src="/assets/video/blob-di.mp4" type="video/mp4" />
                </video>
              </div>
            </div>

            <div style={{ textAlign: 'center' }}>
              <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.12em', color: 'var(--safe)', marginBottom: 12 }}>
                02 -- AI SECURITY ANALYST
              </p>
              <h3 style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 'clamp(48px, 6vw, 72px)', letterSpacing: '0.08em', lineHeight: 0.9, marginBottom: 16, color: 'var(--safe)' }}>
                DAYE
              </h3>
              <p style={{ color: 'var(--ovw-0p8)', fontSize: 15, lineHeight: 1.65, marginBottom: 10, maxWidth: 440, margin: '0 auto 10px' }}>
                Ask anything. DAYE explains threats in plain language and gives you a concrete next step. Like having a security analyst on call 24/7.
              </p>
              <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, color: 'var(--ovw-0p4)', marginBottom: 24 }}>
                VOICE · FILE ANALYSIS · REAL-TIME INTEL · GLOBE BRIEFS
              </p>
              <motion.button
                whileHover={{ scale: 1.04, boxShadow: '0 0 40px rgba(48,209,88,0.3)' }}
                whileTap={{ scale: 0.97 }}
                onClick={() => navigate('/auth')}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 10,
                  padding: '13px 32px',
                  background: 'var(--safe)',
                  color: '#000',
                  fontFamily: 'Inter',
                  fontWeight: 700,
                  fontSize: 14,
                  border: 'none',
                  borderRadius: 12,
                  cursor: 'pointer',
                }}
              >
                Chat with DAYE
              </motion.button>
            </div>
          </motion.div>

        </div>
      </section>

      {/* ─── DEEP FAKE INTELLIGENCE — full storytelling ─── */}
      <section style={{ padding: 'clamp(60px,10vw,120px) clamp(20px,4vw,48px)', background: 'var(--void)' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 'clamp(48px,8vw,80px)' }}>
            <p style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.05em', color: 'var(--ovw-0p25)', marginBottom: 16 }}>
              [ HOW WE SEE THROUGH THE FAKE ]
            </p>
            <h2 className="gsap-heading" style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(36px, 6vw, 80px)', lineHeight: 0.92 }}>
              The science behind<br />every verdict.
            </h2>
          </div>

          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'clamp(32px,5vw,60px)', alignItems: 'flex-start' }}>
            {/* Left — steps + models + CTA */}
            <motion.div {...IN_VIEW} style={{ flex: '1 1 300px' }}>
              {[
                { n: '01', title: 'Biometric mesh analysis', desc: 'We map 468 facial landmarks using MediaPipe. Any AI-generated face leaves geometric inconsistencies invisible to the human eye.' },
                { n: '02', title: '3D model reconstruction', desc: "Real faces have natural depth variance. Deepfakes fail the 3D scan — normals, shadows, and reflection vectors don't align." },
                { n: '03', title: 'Identity signature matching', desc: 'We cross-reference against known deepfake architecture signatures: GAN artifacts, frequency domain anomalies, compression tells.' },
              ].map(({ n, title, desc }) => (
                <div key={n} style={{ display: 'flex', gap: 20, marginBottom: 36 }}>
                  <span style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 13, color: 'var(--ovw-0p15)', flexShrink: 0, paddingTop: 3 }}>{n}</span>
                  <div>
                    <p style={{ fontFamily: 'Inter', fontWeight: 700, fontSize: 16, color: 'var(--text-1)', marginBottom: 8 }}>{title}</p>
                    <p style={{ fontFamily: 'Inter', fontSize: 14, color: 'var(--ovw-0p45)', lineHeight: 1.65 }}>{desc}</p>
                  </div>
                </div>
              ))}

              <p style={{ fontFamily: 'Inter', fontSize: 10, letterSpacing: '0.06em', color: 'var(--ovw-0p2)', marginBottom: 24 }}>
                POWERED BY: HIVE AI · XCEPTIONNET · EFFICIENTNET · MESONET
              </p>

              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 36 }}>
                {[{ label: '99.7%', sub: 'ACCURACY' }, { label: '<3s', sub: 'ANALYSIS' }, { label: '50+', sub: 'AI MODELS' }, { label: '1M+', sub: 'MEDIA SCANNED' }].map(({ label, sub }) => (
                  <div key={sub} style={{ padding: '10px 16px', background: 'var(--ovw-0p04)', border: '1px solid var(--ovw-0p08)', borderRadius: 10 }}>
                    <p style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 16, color: 'var(--text-1)', lineHeight: 1 }}>{label}</p>
                    <p style={{ fontFamily: 'Inter', fontSize: 9, letterSpacing: '0.06em', color: 'var(--ovw-0p3)', marginTop: 3 }}>{sub}</p>
                  </div>
                ))}
              </div>

              <motion.button
                whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.97 }}
                onClick={() => navigate('/auth')}
                style={{ padding: '14px 36px', background: 'var(--chrome-white)', color: 'var(--void)', fontFamily: 'Inter', fontWeight: 700, fontSize: 14, border: 'none', borderRadius: 10 }}
              >
                Try Deep Fake Detection
              </motion.button>
            </motion.div>

            {/* Right — image grid */}
            <motion.div
              initial={{ opacity: 0, x: 40 }} whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.9, delay: 0.15, ease: [0.25, 0.1, 0.25, 1] }}
              viewport={{ once: true, margin: '-60px' }}
              style={{ flex: '1 1 300px', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gridTemplateRows: 'auto auto', gap: 8 }}
            >
              {/* Featured full-width */}
              <div style={{ gridColumn: '1 / -1', position: 'relative', borderRadius: 16, overflow: 'hidden', height: 'clamp(180px,22vw,260px)' }}>
                <img src="/assets/video/a6d0630ce28473947929efbcdbc53445.jpg" alt="Authentic vs Fake detection" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
                <div style={{ position: 'absolute', top: 12, right: 12, background: 'rgba(255,45,45,0.9)', padding: '4px 10px', borderRadius: 6 }}>
                  <span style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 10, color: '#fff', letterSpacing: '0.04em' }}>97% FAKE</span>
                </div>
                <div style={{ position: 'absolute', bottom: 12, left: 12 }}>
                  <span style={{ fontFamily: 'Inter', fontSize: 9, letterSpacing: '0.08em', color: 'var(--ovw-0p5)' }}>AUTHENTIC vs FAKE</span>
                </div>
              </div>

              {/* 3 small images */}
              {[
                { src: '/assets/video/59e3fe10b1baae0eb4fd232ffd49d868.jpg', label: 'MESH DETECTION' },
                { src: '/assets/video/10ca8356801affed229c007c8bddf93c.jpg', label: '3D MODEL SCAN' },
                { src: '/assets/video/d56c1633639c7480b16bfeac3e525dc6.jpg', label: 'IDENTITY MASKED' },
              ].map(({ src, label }) => (
                <div key={label} style={{ position: 'relative', borderRadius: 12, overflow: 'hidden', height: 'clamp(80px,10vw,110px)' }}>
                  <img src={src} alt={label} style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
                  <div style={{ position: 'absolute', bottom: 6, left: 6 }}>
                    <span style={{ fontFamily: 'Inter', fontSize: 8, letterSpacing: '0.06em', color: 'var(--ovw-0p5)' }}>{label}</span>
                  </div>
                </div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── DAYE CINEMATIC SECTION ─────────────────────── */}
      {/* Pinned to a fixed dark backdrop rather than var(--void): the vignette below only reaches 75% black at
          the edges and stays transparent through the center, so on the light --void it netted out as a washed
          grey instead of the intended always-dark atmospheric section (the green accents below are already
          pinned on that assumption). */}
      <section style={{ position: 'relative', overflow: 'hidden', background: '#09090b', padding: 'clamp(48px,7vw,80px) clamp(20px,5vw,60px)' }}>
        {/* Perspective room grid image background */}
        <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none', overflow: 'hidden' }}>
          <img src="/assets/video/22ee8c4a4ffcfe6b8012f297b4232309.jpg" alt="" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center', opacity: 0.4 }} />
          {/* Green tint over grid */}
          <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse at center, rgba(48,209,88,0.06) 0%, transparent 65%)' }} />
          {/* Darken edges */}
          <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse at center, transparent 30%, rgba(0,0,0,0.75) 100%)' }} />
        </div>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 60, alignItems: 'center' }}>
          {/* Left — typography. This section's vignette darkens toward the edges up to 75% black regardless of
              theme (an intentional atmospheric section, like the hero), so its green accents stay fixed to the
              vibrant dark-mode green rather than the light-mode --safe (tuned for a light page), which would be
              low-contrast against this background. */}
          <motion.div {...IN_VIEW}>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.2em', color: 'rgba(48,209,88,0.5)', marginBottom: 16 }}>MEET YOUR ANALYST</p>
            <h2 style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 'clamp(80px, 14vw, 160px)', letterSpacing: '0.05em', color: '#30D158', lineHeight: 0.85, marginBottom: 24 }}>DAYE</h2>
            <p style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontWeight: 400, fontSize: 'clamp(16px, 2vw, 20px)', color: 'rgba(255,255,255,0.81)', lineHeight: 1.65, marginBottom: 36, maxWidth: 460 }}>
              A cybersecurity intelligence analyst powered by AI. Understands context, speaks plainly, acts fast. Available every second of every day.
            </p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 40 }}>
              {['Voice Intelligence', 'File Analysis', 'Chat', 'Globe Briefs', 'Real-time Intel'].map((pill) => (
                <span key={pill} style={{ fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.1em', color: '#30D158', background: 'rgba(48,209,88,0.08)', border: '1px solid rgba(48,209,88,0.2)', padding: '6px 14px', borderRadius: 20 }}>{pill}</span>
              ))}
            </div>
            <motion.button
              whileHover={{ scale: 1.04, boxShadow: '0 0 40px rgba(48,209,88,0.18)' }}
              whileTap={{ scale: 0.97 }}
              onClick={() => navigate('/auth')}
              style={{ padding: '14px 36px', background: '#30D158', color: '#000', fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 18, letterSpacing: '0.08em', border: 'none', borderRadius: 12, cursor: 'pointer' }}
            >
              Chat with DAYE
            </motion.button>
          </motion.div>

          {/* Right — mini popup mockup */}
          <motion.div
            initial={{ opacity: 0, x: 40 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.9, delay: 0.2, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true, margin: '-60px' }}
            style={{ display: 'flex', justifyContent: 'center' }}
          >
            <div style={{ width: 320, background: 'rgba(12,12,16,0.95)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 20, overflow: 'hidden', boxShadow: '0 40px 80px rgba(0,0,0,0.6)' }}>
              {/* Popup header — fixed-dark mockup window, text stays fixed light regardless of theme */}
              <div style={{ padding: '12px 16px', borderBottom: '1px solid rgba(255,255,255,0.09)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <div style={{ width: 8, height: 8, borderRadius: '50%', background: '#30D158', boxShadow: '0 0 8px rgba(48,209,88,0.6)' }} />
                  <span style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 14, letterSpacing: '0.12em', color: '#F5F5F7' }}>DAYE</span>
                </div>
                <span style={{ fontFamily: 'JetBrains Mono', fontSize: 9, color: '#30D158', letterSpacing: '0.08em' }}>ONLINE</span>
              </div>
              {/* Chat bubbles */}
              <div style={{ padding: '16px', display: 'flex', flexDirection: 'column', gap: 10 }}>
                {[
                  { role: 'daye', text: 'I detected a phishing pattern in that link. High confidence — 94% match to known BEC infrastructure.' },
                  { role: 'user', text: 'Should I report it?' },
                  { role: 'daye', text: 'Yes. Forward to your IT team and report to phishing@irs.gov. Block the sender immediately.' },
                ].map((msg, i) => (
                  <div key={i} style={{ display: 'flex', justifyContent: msg.role === 'user' ? 'flex-end' : 'flex-start' }}>
                    <div style={{ maxWidth: '80%', padding: '8px 12px', borderRadius: msg.role === 'user' ? '12px 12px 4px 12px' : '12px 12px 12px 4px', background: msg.role === 'user' ? 'rgba(255,255,255,0.1)' : 'rgba(48,209,88,0.1)', border: msg.role === 'user' ? '1px solid rgba(255,255,255,0.1)' : '1px solid rgba(48,209,88,0.2)' }}>
                      <p style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 12, color: msg.role === 'daye' ? '#F5F5F7' : 'rgba(255,255,255,0.88)', lineHeight: 1.5 }}>{msg.text}</p>
                    </div>
                  </div>
                ))}
              </div>
              {/* Input bar mockup — this popup is a fixed-dark chat window mockup, so its text stays fixed light-on-dark */}
              <div style={{ padding: '10px 14px 14px', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 12, padding: '8px 12px' }}>
                  <span style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 12, color: 'rgba(255,255,255,0.56)', flex: 1 }}>Ask DAYE anything...</span>
                  <div style={{ width: 26, height: 26, borderRadius: '50%', background: '#30D158', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                    <span style={{ fontSize: 10 }}>↑</span>
                  </div>
                </div>
              </div>
              {/* Footer */}
              <div style={{ padding: '8px 16px 10px', textAlign: 'center' }}>
                <span style={{ fontFamily: 'JetBrains Mono', fontSize: 8, color: 'rgba(255,255,255,0.5)', letterSpacing: '0.12em' }}>DAYE · INTELLIGENCE ACTIVE</span>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ─── DATA BREACH INTELLIGENCE ────────────────────── */}
      <section style={{ position: 'relative', overflow: 'hidden', padding: 'clamp(60px,10vw,100px) clamp(20px,4vw,48px)', background: 'var(--void)', borderTop: '1px solid var(--ovw-0p05)' }}>
        {/* Danger perspective grid */}
        <div style={{ position: 'absolute', bottom: 0, left: '-10%', right: '-10%', height: '55%', pointerEvents: 'none',
          backgroundImage: 'linear-gradient(rgba(205,133,63,0.04) 1px,transparent 1px),linear-gradient(90deg,rgba(205,133,63,0.04) 1px,transparent 1px)',
          backgroundSize: '50px 50px',
          transform: 'perspective(600px) rotateX(-50deg)',
          transformOrigin: 'bottom center',
          maskImage: 'linear-gradient(to top,transparent 10%,rgba(0,0,0,0.35) 70%,transparent 100%)',
          WebkitMaskImage: 'linear-gradient(to top,transparent 10%,rgba(0,0,0,0.35) 70%,transparent 100%)',
          zIndex: 0,
        }} />
        <div style={{ position: 'absolute', inset: 0, backgroundImage: 'radial-gradient(circle, rgba(205,133,63,0.03) 1px, transparent 1px)', backgroundSize: '30px 30px', pointerEvents: 'none' }} />

        <div style={{ position: 'relative', zIndex: 1, maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 60, alignItems: 'center' }}>

            {/* Label/headline/pills sit directly on the light page (unlike the fixed-dark BREACH REPORT card
                below), so they use a light-mode-only darker gradient/color instead of the dark-mode gold/tan,
                which measured low contrast against the light --void page background. */}
            <style>{`
              .breach-headline{background:linear-gradient(135deg,#D4A44E,#CD853F,#8B4513);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;}
              :root[data-theme='light'] .breach-headline{background:linear-gradient(135deg,#8A5322,#6B3F16,#3D220A);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;}
              .breach-label{color:rgba(205,133,63,0.7);}
              :root[data-theme='light'] .breach-label{color:#6B3F16;}
              .breach-pill{color:rgba(205,133,63,0.7);border-color:rgba(205,133,63,0.2);background:rgba(205,133,63,0.06);}
              :root[data-theme='light'] .breach-pill{color:#5C3812;border-color:rgba(91,58,18,0.35);background:rgba(91,58,18,0.08);}
            `}</style>
            <motion.div {...IN_VIEW} style={{ flex: '1 1 300px' }}>
              <p className="breach-label" style={{ fontFamily: 'JetBrains Mono', fontSize: 11, letterSpacing: '0.2em', marginBottom: 20 }}>
                [ DATA BREACH INTELLIGENCE ]
              </p>
              <h2 className="gsap-heading breach-headline" style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92, marginBottom: 20 }}>
                Your data<br />is already<br />out there.
              </h2>
              <p style={{ color: 'var(--ovw-0p5)', fontSize: 16, maxWidth: 500, lineHeight: 1.65, marginBottom: 36 }}>
                Check any email against 14+ billion leaked credentials. D0B3RMAN searches across hundreds of known data breaches — banks, social networks, healthcare, gaming — and tells you exactly where your data was exposed and what to do next.
              </p>
              <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 36 }}>
                {['14B+ leaked records', '600+ breach sources', 'Instant verdict'].map((feat) => (
                  <span key={feat} className="breach-pill" style={{ padding: '8px 14px', borderWidth: 1, borderStyle: 'solid', borderRadius: 8, fontFamily: 'JetBrains Mono', fontSize: 11 }}>
                    {feat}
                  </span>
                ))}
              </div>
              <motion.button
                whileHover={{ scale: 1.04 }}
                whileTap={{ scale: 0.97 }}
                onClick={() => navigate('/auth')}
                style={{ padding: '14px 36px', background: 'var(--chrome-white)', color: 'var(--void)', fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontWeight: 700, fontSize: 14, border: 'none', borderRadius: 10 }}>
                Check Your Email
              </motion.button>
            </motion.div>

            <motion.div
              {...IN_VIEW}
              className="glass"
              style={{ flex: '1 1 300px', padding: 32, borderRadius: 24, position: 'relative', overflow: 'hidden', minHeight: 380, background: 'rgba(20,10,4,0.92)', border: '1px solid rgba(205,133,63,0.18)' }}
            >
              <div style={{ marginBottom: 20 }}>
                <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.2em', color: 'rgba(205,133,63,0.7)', marginBottom: 8 }}>BREACH REPORT</p>
                <p style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 32, letterSpacing: '0.04em', background: 'linear-gradient(135deg,#D4A44E,#CD853F)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', lineHeight: 1 }}>
                  7 breaches found
                </p>
                {/* This card is a fixed dark "espresso" terminal card (like the rest of its already-hardcoded tan/orange
                    text below) — the ovw and text theme tokens go near-invisible here in light mode, so this and the
                    breach rows below use fixed light values matching the card's own dark background. */}
                <p style={{ fontFamily: 'JetBrains Mono', fontSize: 11, color: 'rgba(230,211,184,0.65)', marginTop: 6 }}>for ██████@email.com</p>
              </div>
              {[
                { name: 'LinkedIn', year: '2021', records: '700M records', types: 'Email · Phone · Salary data' },
                { name: 'Adobe', year: '2013', records: '153M records', types: 'Email · Password hash' },
                { name: 'Canva', year: '2019', records: '137M records', types: 'Email · Username · Location' },
                { name: 'Dropbox', year: '2012', records: '68M records', types: 'Email · Hashed password' },
              ].map((breach) => (
                <div key={breach.name} style={{ padding: '10px 14px', background: 'rgba(205,133,63,0.05)', border: '1px solid rgba(205,133,63,0.14)', borderRadius: 10, marginBottom: 8, display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div style={{ width: 7, height: 7, borderRadius: '50%', background: '#CD853F', flexShrink: 0 }} />
                  <div style={{ flex: 1 }}>
                    <p style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontWeight: 700, fontSize: 13, color: '#F6ECDE', lineHeight: 1.3 }}>
                      {breach.name} <span style={{ fontFamily: 'JetBrains Mono', fontSize: 10, color: 'rgba(230,211,184,0.65)', fontWeight: 400 }}>{breach.year}</span>
                    </p>
                    <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, color: 'rgba(230,211,184,0.65)', marginTop: 2 }}>{breach.types}</p>
                  </div>
                  <span style={{ fontFamily: 'JetBrains Mono', fontSize: 10, color: 'rgba(205,133,63,0.6)', whiteSpace: 'nowrap' }}>{breach.records}</span>
                </div>
              ))}
              <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, color: 'rgba(230,211,184,0.65)', marginTop: 12, textAlign: 'center', letterSpacing: '0.08em' }}>
                + 3 more breaches — sign in to view all
              </p>
            </motion.div>

          </div>
        </div>
      </section>

      {/* ─── CYBER GLOBE — video + text ─────────────────── */}
      <section style={{ position: 'relative', overflow: 'hidden', background: 'var(--void)', padding: 'clamp(80px,12vw,140px) clamp(20px,5vw,60px)' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 60, alignItems: 'center' }}>
          {/* Left — video globe */}
          <motion.div
            initial={{ opacity: 0, x: -40 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.9, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true, margin: '-60px' }}
            style={{ position: 'relative', height: 340, borderRadius: 20, overflow: 'hidden', background: '#000810' }}
          >
            <video autoPlay muted loop playsInline style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', opacity: 0.85 }}>
              <source src="/assets/video/world.mp4" type="video/mp4" />
            </video>
            <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(135deg, rgba(0,20,60,0.3) 0%, transparent 60%)' }} />
            <div style={{ position: 'absolute', top: 16, left: 18 }}>
              <span style={{ fontFamily: 'JetBrains Mono', fontSize: 9, letterSpacing: '0.18em', color: 'rgba(100,160,255,0.6)' }}>LIVE THREAT MAP</span>
            </div>
            <div style={{ position: 'absolute', bottom: 16, left: 16, right: 16, display: 'flex', gap: 10 }}>
              {[{ n: '8', label: 'CRITICAL ZONES' }, { n: '30+', label: 'HIGH RISK' }, { n: '80+', label: 'COUNTRIES' }].map(({ n, label }) => (
                <div key={label} style={{ flex: 1, padding: '8px 10px', background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(12px)', borderRadius: 10, border: '1px solid rgba(255,255,255,0.1)' }}>
                  <p style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 20, color: '#F5F5F7', lineHeight: 1 }}>{n}</p>
                  {/* Fixed dark pill background — label stays fixed light rather than the theme-swapping token */}
                  <p style={{ fontFamily: 'JetBrains Mono', fontSize: 8, color: 'rgba(255,255,255,0.68)', letterSpacing: '0.08em' }}>{label}</p>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Right — text */}
          <motion.div {...IN_VIEW} style={{ textAlign: 'right' }}>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, letterSpacing: '0.2em', color: 'rgba(100,160,255,0.5)', marginBottom: 16 }}>GLOBAL CYBER INTELLIGENCE</p>
            <h2 style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 80px)', lineHeight: 0.92, marginBottom: 24 }}>
              The world's<br />cyber threats.
            </h2>
            <p style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontWeight: 400, fontSize: 'clamp(15px, 1.8vw, 18px)', color: 'var(--ovw-0p5)', lineHeight: 1.65, marginBottom: 36 }}>
              Every country. Real threats. DAYE's analysis. See where attacks originate, track risk scores, and get live intelligence briefs for any nation on Earth.
            </p>
            <motion.button
              whileHover={{ scale: 1.04, boxShadow: '0 0 40px rgba(100,160,255,0.15)' }}
              whileTap={{ scale: 0.97 }}
              onClick={() => navigate('/auth')}
              style={{ padding: '14px 36px', background: 'rgba(100,160,255,0.12)', color: '#6AA0FF', fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 18, letterSpacing: '0.08em', border: '1px solid rgba(100,160,255,0.25)', borderRadius: 12, cursor: 'pointer' }}
            >
              Open Cyber Globe
            </motion.button>
          </motion.div>
        </div>
      </section>

      {/* ─── STATS ROW ───────────────────────────────────── */}
      <div style={{ padding: '80px clamp(20px,4vw,48px)', borderTop: '1px solid var(--ovw-0p05)', borderBottom: '1px solid var(--ovw-0p05)', background: 'var(--void)' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 40, textAlign: 'center' }}>
          {[
            { target: 400, suffix: '%', label: 'Rise in deepfake attacks' },
            { target: 70, suffix: '%', label: 'IoT devices with critical vulns' },
            { target: 4, suffix: 'M+', prefix: '$', label: 'Average breach cost' },
            { target: 2, suffix: ' modules', label: 'One platform' },
          ].map((stat, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 48 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: i * 0.1, ease: [0.25, 0.1, 0.25, 1] }}
              viewport={{ once: true, margin: '-60px' }}
            >
              <div style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(40px, 5vw, 64px)', lineHeight: 1, marginBottom: 8 }}>
                <AnimatedCounter target={stat.target} prefix={stat.prefix} suffix={stat.suffix} />
              </div>
              <p style={{ fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p25)', letterSpacing: '0.03em' }}>
                {stat.label.toUpperCase()}
              </p>
            </motion.div>
          ))}
        </div>
      </div>

      {/* ─── HORIZONTAL PINNED SCROLL ────────────────────── */}
      <div ref={hContainerRef} className="h-container" style={{ overflow: 'hidden' }}>
        <div style={{ display: 'flex', width: `${hPanels.length * 100}vw`, height: '100vh' }}>
          {hPanels.map((panel, i) => (
            <div
              key={i}
              className="h-panel"
              style={{ width: '100vw', height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden', background: '#09090b' }}
            >
              {/* Panel background pinned to fixed black rather than var(--void): the video is composited with
                  the default "screen" blend, which only makes its black background disappear when the backdrop
                  behind it is actually black — against the light --void it washed white, and swapping the blend
                  mode itself just traded that for a flat grey smear (the video's own black frame painted opaque). */}
              <VideoBlob src="/assets/video/blob-news.mp4" cover opacity={0.25} style={{ zIndex: 0 }} />
              {/* The .glass class's own background/border are theme-adaptive (a light tint on dark mode's black
                  panel, but a dark tint on this now-permanently-black panel in light mode — i.e. invisible), so
                  they're pinned here to the same light-on-black values dark mode already resolved to, and the
                  text inside is pinned to fixed white/light rather than the ink-on-white tokens that went
                  near-black-on-black once this panel stopped following the page theme. */}
              <div
                className="glass"
                style={{
                  position: 'relative', zIndex: 1, padding: 'clamp(32px,6vw,60px) clamp(24px,7vw,72px)', borderRadius: 32, maxWidth: 600, textAlign: 'center',
                  background: 'rgba(255,255,255,0.073)', border: '1px solid rgba(255,255,255,0.194)',
                  boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.542), inset 0 -1px 0 rgba(255,255,255,0.078), 0 4px 6px rgba(0,0,0,0.15), 0 32px 64px rgba(0,0,0,0.4)',
                }}
              >
                <p style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.06em', color: 'rgba(255,255,255,0.58)', marginBottom: 20 }}>
                  {panel.num} -- {panel.module}
                </p>
                <h2 style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(28px, 8vw, 96px)', lineHeight: 0.9, whiteSpace: 'pre-line', marginBottom: 32, color: '#FFFFFF' }}>
                  {panel.headline}
                </h2>
                <p style={{ fontFamily: 'Inter', fontSize: 18, color: 'rgba(255,255,255,0.76)', lineHeight: 1.6 }}>
                  {panel.sub}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ─── NEWS SECTION ────────────────────────────────── */}
      <section id="news" style={{ position: 'relative', overflow: 'hidden', padding: 'clamp(60px,10vw,100px) clamp(20px,4vw,48px)', background: 'var(--void)' }}>
        <div style={{ position: 'relative', zIndex: 1, maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 60, alignItems: 'center' }}>
            <motion.div {...IN_VIEW} style={{ flex: '1 1 300px' }}>
              <p style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.05em', color: 'var(--danger)', marginBottom: 20 }}>
                [ FAKE NEWS DETECTION ]
              </p>
              <h2 className="gsap-heading" style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92, marginBottom: 20 }}>
                Don't believe<br />everything<br />you read.
              </h2>
              <p style={{ color: 'var(--ovw-0p5)', fontSize: 16, maxWidth: 500, lineHeight: 1.65, marginBottom: 36 }}>
                Paste any headline, claim, or article URL. D0B3RMAN cross-references it,
                checks source quality, and gives you a credibility verdict in seconds.
              </p>
              <motion.button
                whileHover={{ scale: 1.04 }}
                whileTap={{ scale: 0.97 }}
                onClick={() => navigate('/auth')}
                style={{ padding: '14px 36px', background: 'var(--chrome-white)', color: 'var(--void)', fontFamily: 'Inter', fontWeight: 700, fontSize: 14, border: 'none', borderRadius: 10 }}>
                Try News Verification
              </motion.button>
            </motion.div>

            {/* Pinned to fixed black rather than the .glass class's theme-adaptive tint: the video behind it relies
                on the default "screen" blend to make its own black background disappear, which only works
                against a guaranteed-black backdrop — text below is pinned to fixed light/bright-red values to
                match, since the theme-swapping tokens would go near-invisible on a card that no longer varies. */}
            <motion.div
              {...IN_VIEW}
              className="glass"
              style={{ flex: '1 1 300px', padding: 40, borderRadius: 24, position: 'relative', overflow: 'hidden', minHeight: 360, display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', background: '#09090b' }}
            >
              <VideoBlob src="/assets/video/blob-news.mp4" cover opacity={0.4} style={{ zIndex: 0 }} />
              <div style={{ position: 'relative', zIndex: 1 }}>
                <p style={{ fontFamily: 'Inter', fontSize: 10, letterSpacing: '0.04em', color: '#FF2D2D', marginBottom: 16 }}>VERDICT -- LIKELY FALSE</p>
                <p style={{ fontFamily: 'Inter', fontWeight: 700, fontSize: 18, lineHeight: 1.4, marginBottom: 12, color: '#FFFFFF' }}>"Breaking: Scientists Confirm AI Will Replace All Jobs By 2025"</p>
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                  {['Sensationalist framing', 'No primary source', 'Vague attribution'].map((flag) => (
                    <span key={flag} style={{ fontFamily: 'Inter', fontSize: 10, color: '#FF2D2D', background: 'rgba(255,45,45,0.12)', border: '1px solid rgba(255,45,45,0.25)', padding: '4px 10px', borderRadius: 4 }}>{flag}</span>
                  ))}
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── LIVE INTEL FEED (Samsung News style) ───────── */}
      <section style={{ minHeight: '100vh', background: 'var(--void)', borderTop: '1px solid var(--ovw-0p06)', display: 'flex', flexDirection: 'column', padding: 'clamp(40px,6vw,60px) clamp(20px,4vw,48px)' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', width: '100%', flex: 1, display: 'flex', flexDirection: 'column' }}>

          {/* Header */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <div style={{ width: 7, height: 7, borderRadius: '50%', background: 'var(--danger)', animation: 'landingPulse 1.5s infinite' }} />
              <span style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.05em', color: 'var(--ovw-0p3)' }}>LIVE</span>
            </div>
            <span style={{ fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p25)' }}>
              {new Date().toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' }).toUpperCase()}
            </span>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 24 }}>
            <h2 style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(24px, 4vw, 36px)' }}>Top Stories</h2>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" style={{ color: 'var(--ovw-0p5)' }}>
              <path d="M9 18l6-6-6-6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </div>

          {/* Hero story — real person image */}
          <motion.div
            initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }} viewport={{ once: true }}
            onClick={() => navigate('/auth')}
            style={{ borderRadius: 16, overflow: 'hidden', position: 'relative', height: 'clamp(220px, 38vh, 340px)', marginBottom: 4, flexShrink: 0, cursor: 'pointer' }}
          >
            <img
              src="/assets/video/59e67eaeb4601648a3e3e9d9e441c447.jpg"
              alt=""
              style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center top', pointerEvents: 'none' }}
            />
            <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to bottom, rgba(0,0,0,0.05) 0%, rgba(0,0,0,0.92) 100%)' }} />
            <div style={{ position: 'absolute', inset: 0, padding: '24px 28px', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', zIndex: 1 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
                <div style={{ width: 20, height: 20, borderRadius: 4, background: 'rgba(255,45,45,0.9)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <span style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 10, color: '#fff' }}>R</span>
                </div>
                <span style={{ fontFamily: 'Inter', fontWeight: 700, fontSize: 13, color: 'rgba(255,255,255,0.94)' }}>REUTERS</span>
                <span style={{ fontFamily: 'Inter', fontSize: 13, color: 'rgba(255,255,255,0.75)' }}>2 hours ago</span>
              </div>
              <h3 style={{ fontFamily: 'Inter', fontWeight: 700, fontSize: 'clamp(17px, 2.5vw, 22px)', lineHeight: 1.3, color: '#fff', maxWidth: 680 }}>
                Deepfake video of former US president spreads across platforms ahead of election, millions fooled before takedown
              </h3>
            </div>
          </motion.div>

          {/* Story list */}
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
            {[
              { source: 'DARK READING', text: 'AI-generated deepfake audio used in $25M corporate wire transfer fraud targeting CEO', time: '11m ago', color: '#FF9500', img: '/assets/video/a6d0630ce28473947929efbcdbc53445.jpg' },
              { source: 'BLEEPING COMPUTER', text: 'Massive botnet of 40,000 compromised IoT cameras targeting financial sector', time: '28m ago', color: '#FF6B35', img: '/assets/video/ca047a55c45f5adbd43df958c3487fee.jpg' },
              { source: 'THE HACKER NEWS', text: 'State-sponsored group deploys rootkit via malicious firmware updates to routers', time: '44m ago', color: '#FF2D2D', img: '/assets/video/d56c1633639c7480b16bfeac3e525dc6.jpg' },
              { source: 'KREBS ON SECURITY', text: 'Ransomware group LockBit 4.0 claims breach of three critical infrastructure operators', time: '3h ago', color: '#FF6B35', img: '/assets/video/538ca00c1c1483acef1e8ccea3565f9d.jpg' },
            ].map((item, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 8 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.06 }} viewport={{ once: true }}
                onClick={() => navigate('/auth')}
                style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '16px 0', borderBottom: '1px solid var(--ovw-0p06)', cursor: 'pointer' }}
              >
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                    <div style={{ width: 18, height: 18, borderRadius: 4, background: item.color + '22', border: `1px solid ${item.color}44`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                      <span style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 9, color: item.color }}>{item.source[0]}</span>
                    </div>
                    <span style={{ fontFamily: 'Inter', fontWeight: 700, fontSize: 13, color: 'var(--ovw-0p55)' }}>{item.source}</span>
                  </div>
                  <p style={{ fontFamily: 'Inter', fontWeight: 600, fontSize: 'clamp(14px, 1.8vw, 16px)', color: 'var(--text-1)', lineHeight: 1.35, marginBottom: 6, overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' }}>
                    {item.text}
                  </p>
                  <span style={{ fontFamily: 'Inter', fontSize: 13, color: 'var(--ovw-0p35)' }}>{item.time}</span>
                </div>
                <div style={{ width: 88, height: 68, borderRadius: 10, flexShrink: 0, overflow: 'hidden', border: `1px solid ${item.color}22` }}>
                  <img src={item.img} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center top', display: 'block' }} />
                </div>
              </motion.div>
            ))}

            {/* CTA */}
            <motion.button
              whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
              onClick={() => navigate('/auth')}
              style={{ marginTop: 32, padding: '16px', background: 'var(--ovw-0p04)', border: '1px solid var(--ovw-0p1)', borderRadius: 12, fontFamily: 'Inter', fontWeight: 700, fontSize: 15, color: 'var(--ovw-0p7)', width: '100%', maxWidth: 320, alignSelf: 'center' }}
            >
              Verify any headline free →
            </motion.button>
          </div>
        </div>
        <style>{`@keyframes landingPulse { 0%,100%{opacity:1} 50%{opacity:0.4} }`}</style>
      </section>

      {/* ─── EXTENSION SECTION ───────────────────────────── */}
      <section id="extension" style={{ padding: 'clamp(60px,10vw,100px) clamp(20px,4vw,48px)', borderTop: '1px solid var(--ovw-0p05)', background: 'var(--void)' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 60, alignItems: 'center' }}>
            <motion.div {...IN_VIEW} style={{ flex: '1 1 300px' }}>
              <p style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.05em', color: 'var(--ovw-0p25)', marginBottom: 20 }}>[ BROWSER EXTENSION ]</p>
              <h2 className="gsap-heading" style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92, marginBottom: 20 }}>
                D0B3RMAN<br />everywhere<br />you browse.
              </h2>
              <p style={{ color: 'var(--ovw-0p5)', fontSize: 16, maxWidth: 500, lineHeight: 1.65, marginBottom: 36 }}>
                Right-click any image, video, or selected text on any website.
                Results appear in a floating panel — without leaving the page.
              </p>
              <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 36 }}>
                {['Right-click any image', 'Selected text verification', 'Works on all sites'].map((feat) => (
                  <span key={feat} style={{ padding: '8px 14px', background: 'var(--ovw-0p04)', backdropFilter: 'blur(20px)', border: '1px solid var(--ovw-0p08)', borderRadius: 8, fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p4)', boxShadow: 'inset 0 1px 0 var(--ovw-0p08)' }}>
                    {feat}
                  </span>
                ))}
              </div>
              <motion.button
                whileHover={{ scale: 1.04, boxShadow: '0 0 30px var(--ovw-0p1)' }}
                whileTap={{ scale: 0.97 }}
                style={{ padding: '14px 36px', background: 'var(--chrome-white)', color: 'var(--void)', fontFamily: 'Inter', fontWeight: 700, fontSize: 14, border: 'none', borderRadius: 10 }}>
                Add to Chrome — Free
              </motion.button>
            </motion.div>

            <motion.div
              {...IN_VIEW}
              className="glass"
              style={{ flex: '1 1 300px', padding: 32, borderRadius: 24, minHeight: 400, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}
            >
              <div style={{ fontFamily: 'Inter', fontSize: 10, letterSpacing: '0.04em', color: 'var(--ovw-0p25)', marginBottom: 24 }}>
                EXTENSION DEMO VIDEO -- /assets/video/extension-demo.mp4
              </div>
              {/* Mockup of the always-dark extension popup UI — fixed background, so its text stays fixed
                  light-on-dark rather than the theme-swapping tokens, which would go near-invisible in light mode. */}
              <div style={{ padding: '24px', background: 'rgba(6,6,6,0.94)', backdropFilter: 'blur(28px)', WebkitBackdropFilter: 'blur(28px)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 20, boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.14)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
                  <span style={{ fontFamily: 'Inter', fontSize: 10, letterSpacing: '0.05em', color: 'rgba(255,255,255,0.71)' }}>D0B3RMAN</span>
                  <span style={{ color: 'rgba(255,255,255,0.61)', fontSize: 18, lineHeight: 1 }}>×</span>
                </div>
                <div style={{ fontFamily: 'Inter', fontSize: 64, fontWeight: 700, color: '#FF2D2D', lineHeight: 1, marginBottom: 4 }}>97<span style={{ fontSize: 28 }}>%</span></div>
                <div style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.04em', color: '#FF2D2D', marginBottom: 12 }}>FAKE</div>
                <p style={{ fontFamily: 'Inter', fontSize: 12, color: 'rgba(255,255,255,0.76)', lineHeight: 1.55, marginBottom: 16 }}>
                  This image shows strong deepfake indicators. The facial boundaries and lighting are inconsistent with authentic photography.
                </p>
                <div style={{ display: 'block', textAlign: 'center', padding: '10px', background: 'var(--chrome-white)', color: 'var(--void)', borderRadius: 10, fontFamily: 'Inter', fontSize: 12, fontWeight: 700 }}>
                  VIEW FULL REPORT
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── REVIEWS ─────────────────────────────────────── */}
      <section id="reviews" style={{ padding: 'clamp(60px,8vw,100px) 0 clamp(60px,8vw,100px) clamp(20px,4vw,48px)', overflow: 'hidden', background: 'var(--void)' }}>
        <motion.div {...IN_VIEW} style={{ maxWidth: 1200, marginBottom: 56 }}>
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            whileInView={{ opacity: 1, scale: 1 }}
            transition={{ duration: 1.0, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true }}
            style={{ margin: '0 auto 40px', borderRadius: 20, overflow: 'hidden', width: '100%', maxWidth: 1120, height: 'clamp(240px,35vw,420px)', position: 'relative' }}
          >
            <img
              src="/assets/video/b78ad4f230a4015d24a420fce2a7d53b.jpg"
              alt="Doberman"
              style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center top', display: 'block' }}
            />
            {/* No text sits on this photo — the fade exists purely to blend its bottom edge into the page, so it
                targets the actual page background color instead of a hardcoded black that would leave a hard
                seam against a light page. */}
            <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: '40%', background: 'linear-gradient(to bottom, transparent, var(--void))' }} />
          </motion.div>
          <p style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.05em', color: 'var(--ovw-0p25)', marginBottom: 20 }}>[ WHAT USERS SAY ]</p>
          <h2 className="gsap-heading" style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(40px, 7vw, 88px)', lineHeight: 0.92 }}>
            The dog<br />delivers.
          </h2>
        </motion.div>

        <motion.div
          drag="x"
          dragConstraints={{ right: 0, left: -(reviews.length * 380) }}
          style={{ display: 'flex', gap: 20, width: 'max-content', cursor: 'grab' }}
        >
          {reviews.map((r, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              whileHover={{ y: -8, rotate: 0, transition: { duration: 0.2 } }}
              style={{
                width: 360,
                padding: 32,
                flexShrink: 0,
                position: 'relative',
                overflow: 'hidden',
                rotate: r.rotate,
                background: 'var(--ovw-0p04)',
                backdropFilter: 'blur(40px)',
                WebkitBackdropFilter: 'blur(40px)',
                border: '1px solid var(--ovw-0p1)',
                borderRadius: 20,
                boxShadow: 'inset 0 1px 0 var(--ovw-0p18), 0 24px 48px rgba(0,0,0,0.5)',
              }}
            >
              <span style={{ position: 'absolute', top: 20, right: 20, fontFamily: 'Inter', fontSize: 10, letterSpacing: '0.04em', color: r.badgeColor, background: `${r.badgeColor}22`, border: `1px solid ${r.badgeColor}44`, padding: '3px 8px', borderRadius: 4 }}>
                {r.badge}
              </span>
              <p style={{ fontFamily: 'Inter', fontSize: 15, color: 'var(--ovw-0p55)', lineHeight: 1.65, marginBottom: 24, marginTop: 8 }}>"{r.text}"</p>
              {/* This card's background is theme-adaptive (var(--ovw-0p04) over the page), so the author name must follow
                  the theme too — 'white' was a dark-mode leftover, invisible on the light-mode card. */}
              <p style={{ fontFamily: 'Inter', fontWeight: 700, fontSize: 14, color: 'var(--text-1)' }}>{r.author}</p>
              <p style={{ fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p25)', marginTop: 4 }}>{r.role}</p>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* ─── FINAL CTA ───────────────────────────────────── */}
      <section style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden', background: 'var(--void)' }}>
        <div style={{ position: 'relative', zIndex: 1, padding: '0 24px', display: 'flex', flexDirection: 'column', alignItems: 'center', width: '100%', maxWidth: 720 }}>
          {/* Single blob video, contained in a black squircle matching its own baked-in black background — there
              used to be two overlapping copies here (one full-bleed behind the card via a mismatched theme-adaptive
              squircle, near-invisible under the opaque card; one loose/unmasked floating above it), which is why
              the squircle never actually seemed to contain the visible blob. Now there's one, sized and tucked
              to overlap the card the same way the original floating video did. */}
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: -28 }}>
            <div style={{ position: 'relative', width: 'clamp(220px, 34vw, 320px)', height: 'clamp(220px, 34vw, 320px)', borderRadius: '22%', overflow: 'hidden', background: '#050505' }}>
              <video
                autoPlay muted loop playsInline preload="auto"
                style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', display: 'block' }}
              >
                <source src="/assets/video/blob-hero-2.mp4" type="video/mp4" />
              </video>
            </div>
          </div>
          <motion.div
            initial={{ opacity: 0, scale: 0.94, y: 40 }}
            whileInView={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 0.9, ease: [0.25, 0.1, 0.25, 1] }}
            viewport={{ once: true }}
            className="glass"
            style={{ padding: 'clamp(40px,8vw,90px) clamp(20px,6vw,72px)', borderRadius: 36, textAlign: 'center', width: '100%' }}
          >
            <p style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.05em', color: 'var(--ovw-0p25)', marginBottom: 28 }}>
              THE WATCHDOG IS READY
            </p>
            <h2 className="gsap-heading" style={{ fontFamily: 'Inter', fontWeight: 800, fontSize: 'clamp(32px, 6vw, 72px)', lineHeight: 0.92, marginBottom: 36, textAlign: 'center' }}>
              Deploy<br />D0B3RMAN.
            </h2>
            <p style={{ fontFamily: 'Inter', fontSize: 17, color: 'var(--ovw-0p5)', marginBottom: 52 }}>
              Free tier. No credit card. No limits on intelligence.
            </p>
            <motion.button
              whileHover={{ scale: 1.05, boxShadow: '0 0 60px var(--ovw-0p25)' }}
              whileTap={{ scale: 0.96 }}
              onClick={(e) => { shockwave(e); navigate('/auth') }}
              style={{ padding: '20px 72px', background: 'var(--chrome-white)', color: 'var(--void)', fontFamily: 'Inter', fontWeight: 700, fontSize: 17, border: 'none', borderRadius: 14 }}>
              Get Started Free
            </motion.button>
            <p style={{ fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p2)', marginTop: 20 }}>
              3 free scans per module per day -- no card required
            </p>
          </motion.div>
        </div>
      </section>

      {/* ─── TECHNICAL REPORT BANNER ─────────────────────── */}
      <div style={{ borderTop: '1px solid var(--ovw-0p06)', padding: '28px clamp(20px,4vw,48px)', background: 'var(--void)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <div style={{ width: 44, height: 44, borderRadius: 10, background: 'rgba(48,209,88,0.06)', border: '1px solid rgba(48,209,88,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, overflow: 'hidden' }}>
            <img
              src="/pcu-logo.jpeg"
              alt="PCU"
              style={{ width: 36, height: 36, objectFit: 'contain' }}
              onError={(e) => {
                const el = e.currentTarget as HTMLImageElement
                el.style.display = 'none'
                const svg = document.createElement('div')
                svg.innerHTML = '<svg width="16" height="16" fill="none" stroke="rgba(48,209,88,0.9)" stroke-width="1.5" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10,9 9,9 8,9"/></svg>'
                el.parentElement?.appendChild(svg.firstChild as Node)
              }}
            />
          </div>
          <div>
            <p style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontWeight: 700, fontSize: 13, color: 'var(--ovw-0p75)', marginBottom: 2 }}>Final Year Technical Report</p>
            <p style={{ fontFamily: 'JetBrains Mono', fontSize: 10, color: 'var(--ovw-0p25)' }}>B.Sc. Cyber Security — Precious Cornerstone University, Ibadan</p>
          </div>
        </div>
        <motion.button
          whileHover={{ scale: 1.04 }}
          whileTap={{ scale: 0.97 }}
          onClick={() => navigate('/auth')}
          style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 20px', background: 'rgba(48,209,88,0.1)', border: '1px solid rgba(48,209,88,0.25)', borderRadius: 10, color: 'rgba(48,209,88,0.9)', fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontWeight: 700, fontSize: 12 }}
        >
          View Technical Report
          <svg width="13" height="13" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><polyline points="9,18 15,12 9,6"/></svg>
        </motion.button>
      </div>

      {/* ─── FOOTER ──────────────────────────────────────── */}
      <footer style={{ borderTop: '1px solid var(--ovw-0p04)', padding: '32px clamp(20px,4vw,48px)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--void)', flexWrap: 'wrap', gap: 20 }}>
        <span style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", Inter, sans-serif', fontSize: 18, letterSpacing: '0.2em' }}>D0B3RMAN</span>
        <div style={{ display: 'flex', gap: 32, fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p2)' }}>
          <a href="/privacy" style={{ color: 'inherit', textDecoration: 'none' }}>Privacy</a>
          <a href="/terms" style={{ color: 'inherit', textDecoration: 'none' }}>Terms</a>
          <a href="mailto:hello@d0b3rman.ai" style={{ color: 'inherit', textDecoration: 'none' }}>Contact</a>
          <a href="/report" style={{ color: 'inherit', textDecoration: 'none' }}>Technical Report</a>
        </div>
        <p style={{ fontFamily: 'Inter', fontSize: 11, color: 'var(--ovw-0p2)' }}>2026 D0B3RMAN. All rights reserved.</p>
      </footer>

    </div>
  )
}
