import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import type { ReactNode } from 'react'

const SF = '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", system-ui, sans-serif'

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{ fontFamily: 'Syne', fontWeight: 700, fontSize: 20, color: 'rgba(255,255,255,0.92)', marginBottom: 14 }}>{title}</h2>
      <div style={{ fontFamily: SF, fontSize: 14.5, color: 'rgba(255,255,255,0.55)', lineHeight: 1.75 }}>{children}</div>
    </section>
  )
}

export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: '#000', color: '#fff' }}>
      <header style={{ padding: '20px clamp(20px,4vw,48px)', borderBottom: '1px solid rgba(255,255,255,0.06)', display: 'flex', alignItems: 'center', gap: 16 }}>
        <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 8, color: 'rgba(255,255,255,0.5)', textDecoration: 'none', fontFamily: SF, fontSize: 13 }}>
          <ArrowLeft size={16} /> Back
        </Link>
        <span style={{ fontFamily: 'Bebas Neue', fontSize: 18, letterSpacing: '0.2em', marginLeft: 'auto' }}>D0B3RMAN</span>
      </header>

      <div style={{ maxWidth: 720, margin: '0 auto', padding: 'clamp(40px,6vw,72px) clamp(20px,4vw,48px) 96px' }}>
        <p style={{ fontFamily: 'Inter', fontSize: 11, letterSpacing: '0.1em', color: 'rgba(255,255,255,0.3)', marginBottom: 12, textTransform: 'uppercase' }}>
          Last updated August 2026
        </p>
        <h1 style={{ fontFamily: 'Bebas Neue', fontSize: 'clamp(40px,6vw,64px)', letterSpacing: '0.03em', lineHeight: 1, marginBottom: 32 }}>
          TERMS OF SERVICE
        </h1>

        <Section title="Using D0B3RMAN">
          <p>
            D0B3RMAN provides automated deepfake detection, content verification, breach checking, and
            threat intelligence. Results are generated by third-party detection models and AI systems and
            are provided as decision support, not a guarantee — always apply your own judgment, especially
            for high-stakes situations.
          </p>
        </Section>

        <Section title="Accounts">
          <p>
            You're responsible for keeping your account credentials secure and for activity under your
            account. Free accounts are subject to daily scan limits shown in-app; these may change.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p style={{ marginBottom: 10 }}>Don't use D0B3RMAN to:</p>
          <ul style={{ paddingLeft: 20, margin: 0 }}>
            <li style={{ marginBottom: 8 }}>Analyze content you don't have the right to process, or to violate someone else's privacy</li>
            <li style={{ marginBottom: 8 }}>Attempt to circumvent scan limits, rate limits, or authentication</li>
            <li style={{ marginBottom: 8 }}>Submit unlawful content, or use results to harass, defame, or deceive others</li>
            <li>Reverse-engineer or resell access to the underlying detection APIs</li>
          </ul>
        </Section>

        <Section title="No warranty">
          <p>
            Detection results (deepfake scores, breach findings, credibility verdicts, threat briefs) are
            provided "as is," generated by third-party models that can be wrong. We don't guarantee
            accuracy, and we're not liable for decisions made based on these results.
          </p>
        </Section>

        <Section title="The browser extension">
          <p>
            The D0B3RMAN browser extension is provided under these same terms. It only acts on content you
            explicitly select via its right-click menu — see our <Link to="/privacy" style={{ color: 'var(--safe)' }}>Privacy Policy</Link> for
            exactly what it accesses and why.
          </p>
        </Section>

        <Section title="Changes">
          <p>
            We may update these terms as the product changes. Continued use after an update means you
            accept the revised terms.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions: <a href="mailto:hello@d0b3rman.ai" style={{ color: 'var(--safe)' }}>hello@d0b3rman.ai</a>
          </p>
        </Section>
      </div>
    </div>
  )
}
