export interface ReportSection {
  id: string
  heading: string
  body: string[]
}

export interface ReportChapter {
  number: string
  title: string
  sections: ReportSection[]
}

export interface Reference {
  number: number
  citation: string
  url?: string
}

export interface ReportData {
  title: string
  subtitle: string
  author: string
  matric: string
  university: string
  department: string
  supervisor: string
  year: string
  abstract: string
  keywords: string[]
  dedication: string
  acknowledgements: string
  chapters: ReportChapter[]
  references: Reference[]
  appendices: { title: string; content: string[] }[]
}

export const REPORT: ReportData = {
  title: 'DOBERMAN',
  subtitle:
    'Design and Implementation of a Multi-Module AI-Powered Cybersecurity Intelligence Platform',
  author: 'OLUSANU JOSHUA BANKOLE',
  matric: '2022/493',
  university: 'PRECIOUS CORNERSTONE UNIVERSITY',
  department: 'Department of Cyber Security',
  supervisor: 'Dr. Osutokun Kemi',
  year: '2025/2026',

  abstract: `The modern digital environment has given rise to three of the most urgent and interrelated threats of our time: the proliferation of synthetic deepfake media, the systemic vulnerability of IoT-connected networks, and the viral spread of AI-generated misinformation. These threats do not operate in isolation; they reinforce one another, exploit the same cognitive biases, and overwhelm users who lack the tools or training to respond. Existing cybersecurity solutions are either narrowly focused on enterprise environments, prohibitively expensive, or technically inaccessible to the average user.

This project presents DOBERMAN, a multi-module, AI-powered cybersecurity intelligence platform designed to make professional-grade threat detection accessible to everyone. The system is built around four core modules: EYES, which detects deepfake manipulation in images, videos, and audio using the Hive AI computer vision engine combined with contextual explanation generated by the Claude Sonnet language model; NOSE, which performs AI-driven IoT network vulnerability assessment by mapping real CVE (Common Vulnerabilities and Exposures) references to user-described devices and generating a prioritised remediation plan; BRAIN, a persistent AI security analyst powered by Anthropic's Claude Sonnet model that provides expert, conversational cybersecurity guidance in plain language; and NEWS, a credibility verification engine that evaluates headlines and article content against known misinformation patterns.

The platform is implemented as a full-stack web application using React 19, TypeScript, and Vite on the frontend, with Supabase providing PostgreSQL database management, row-level security, and serverless edge functions. A companion Chrome extension extends DOBERMAN's detection capabilities to any webpage via right-click context menus. The system demonstrates a novel architecture for orchestrating multiple AI models, specifically Hive AI for computer vision and Anthropic Claude for natural language reasoning, within a single unified platform with shared authentication, usage tracking, and a consistent user experience.

Evaluation of the system demonstrates high deepfake detection accuracy aligned with Hive AI benchmarks, actionable IoT vulnerability insights validated against the NIST National Vulnerability Database, and positive user feedback on the platform's accessibility and clarity. DOBERMAN represents a significant contribution to the democratisation of cybersecurity intelligence.`,

  keywords: [
    'Deepfake Detection',
    'IoT Security',
    'AI-Powered Cybersecurity',
    'Large Language Models',
    'News Verification',
    'Supabase',
    'React',
    'Hive AI',
    'Claude AI',
    'Edge Functions',
  ],

  dedication: `To my family, who believed in me long before I believed in myself.

To every student who has ever stayed up past midnight asking whether the thing they are building actually matters: it does.

And to the internet, which is simultaneously the most dangerous and most beautiful thing humanity has ever made.`,

  acknowledgements: `This project could not have existed without the guidance, patience, and intellectual generosity of Dr. Osutokun Kemi, whose supervision throughout this academic year pushed me to ask harder questions and build better answers. Thank you.

To the faculty and staff of the Department of Cyber Security at Precious Cornerstone University, Ibadan: your commitment to preparing students for the realities of modern security practice has shaped not just this project, but my entire approach to the field.

To my peers in the 2022/2026 cohort, for the late-night debates, the shared frustrations, and the moments of genuine breakthrough that made this journey worthwhile. You know who you are.

Finally, to the open-source community whose tools, documentation, and collective knowledge made a project of this technical ambition possible for a single undergraduate student: this work stands on your shoulders.`,

  chapters: [
    // ─────────────────────────────────────────────────────
    // CHAPTER 1: INTRODUCTION
    // ─────────────────────────────────────────────────────
    {
      number: '1',
      title: 'Introduction',
      sections: [
        {
          id: '1-1',
          heading: '1.1 Background and Motivation',
          body: [
            `Cybersecurity is no longer a concern exclusive to governments, banks, or large corporations. It has become a personal matter, affecting ordinary people in their living rooms, on their phones, and in their daily consumption of information. Three developments in particular have redefined the threat landscape in ways that existing tools have failed to keep pace with.`,
            `The first is the deepfake epidemic. Generative Adversarial Networks (GANs) and diffusion models have made the synthesis of photorealistic fake media trivially accessible. A 2024 industry report documented a 400 per cent year-on-year increase in deepfake attacks [1]. Fabricated videos of executives authorising fraudulent wire transfers, fake audio recordings used in social engineering, and manipulated identity documents now represent a growing category of financial and reputational harm. The average person has no reliable way to distinguish authentic media from synthetic, and that gap is widening.`,
            `The second is the IoT security crisis. The proliferation of smart devices (routers, cameras, smart TVs, thermostats, baby monitors, and dozens of others) has dramatically expanded the attack surface of the typical home or small-business network. Research from security firm Palo Alto Networks found that 70 per cent of IoT devices have at least one unpatched critical vulnerability [2]. These devices are often deployed with default credentials, rarely receive firmware updates, and are virtually invisible to conventional security tooling.`,
            `The third is the misinformation crisis. The volume of AI-generated text content on the internet doubled between 2022 and 2024 [4]. Fabricated news, manipulated headlines, and synthetic social media narratives now spread faster than corrections. Traditional fact-checking organisations cannot scale to match the pace of production, and most users lack the analytical frameworks to evaluate credibility independently.`,
            `These three threats share a common characteristic: they exploit the gap between how things appear and how they actually are. DOBERMAN, the project presented in this report, was conceived as a direct response to that gap. Its name encapsulates its design philosophy: a watchdog that is alert, intelligent, and perpetually vigilant.`,
          ],
        },
        {
          id: '1-2',
          heading: '1.2 Problem Statement',
          body: [
            `Despite the growing severity of threats posed by deepfake media, IoT vulnerabilities, and AI-generated misinformation, access to reliable, easy-to-use cybersecurity intelligence tools remains severely limited for individual users and small organisations. The current market offers fragmented, technically complex, and often prohibitively expensive solutions that assume a level of expertise the average user simply does not have.`,
            `Specifically, the following gaps exist in the current landscape: (i) no single platform addresses deepfake detection, IoT vulnerability assessment, AI security consulting, and news credibility verification in one cohesive user experience; (ii) existing deepfake detection tools often return a confidence score without any explanatory context, leaving users unable to understand or act on the result; (iii) IoT security tools such as Shodan and Nessus require technical configuration far beyond the capability of most home users; (iv) news verification is typically manual and time-consuming, relying on human fact-checkers who cannot operate at the speed of social media.`,
            `The absence of an accessible, AI-augmented, unified platform for personal and small-team cybersecurity intelligence constitutes the core problem this project addresses.`,
          ],
        },
        {
          id: '1-3',
          heading: '1.3 Aims and Objectives',
          body: [
            `The primary aim of this project is to design, implement, and evaluate a multi-module AI-powered cybersecurity intelligence platform that makes professional-grade threat detection accessible to non-expert users.`,
            `The specific objectives are:`,
            `(i) To review the relevant academic literature on deepfake detection, IoT vulnerability assessment, large language models in cybersecurity, and misinformation identification, establishing the theoretical foundation and research gap that motivates this work.`,
            `(ii) To design and implement EYES, a deepfake detection module capable of analysing image, video, and audio media for synthetic manipulation, returning a confidence score and a plain-language explanation.`,
            `(iii) To design and implement NOSE, an IoT vulnerability assessment module that accepts natural-language descriptions of network environments, maps discovered risks to real CVE references, and returns a prioritised remediation action plan.`,
            `(iv) To design and implement BRAIN, an AI security analyst module that enables multi-turn conversational interaction with a cybersecurity expert persona powered by Claude Sonnet, with persistent conversation history.`,
            `(v) To design and implement NEWS, a news credibility verification module that evaluates submitted headlines and article content against known misinformation indicators and returns a structured verdict.`,
            `(vi) To implement a companion Chrome browser extension that extends DOBERMAN's detection capabilities contextually to any webpage.`,
            `(vii) To evaluate the system's technical correctness, usability, and security through a structured testing programme and to present the findings with critical discussion.`,
          ],
        },
        {
          id: '1-4',
          heading: '1.4 Scope and Delimitations',
          body: [
            `DOBERMAN is scoped as a web-based platform targeting individual users and small teams seeking accessible cybersecurity intelligence. The system operates on user-submitted media and descriptions; it does not perform active network scanning, packet capture, or any form of intrusive penetration testing.`,
            `The deepfake detection module (EYES) is limited to media files up to 50MB in size and the formats supported by Hive AI's detection API. The IoT assessment module (NOSE) operates on user-described environments rather than direct network access, which means the quality of the vulnerability report depends on the accuracy and completeness of the user's description. The news verification module (NEWS) assesses credibility based on linguistic and structural indicators rather than real-time fact database lookups.`,
            `The platform operates within the usage constraints of the free tier of the Anthropic Claude and Hive AI APIs. Production deployment would require tier upgrades for high-volume usage. Mobile-native applications are out of scope for this iteration.`,
          ],
        },
        {
          id: '1-5',
          heading: '1.5 Significance of Study',
          body: [
            `This project makes several notable contributions to both academic knowledge and practical cybersecurity capability.`,
            `From a technical standpoint, DOBERMAN demonstrates a novel architecture for orchestrating multiple AI models (specifically, a computer vision API and a large language model) within a single, security-focused platform. The design patterns developed here, particularly the edge function architecture for AI orchestration with built-in rate limiting and RLS-secured data storage, represent a reusable template for AI-augmented security applications.`,
            `From a social standpoint, this project directly addresses the democratisation of cybersecurity. The consistent theme across all four modules is accessibility: results are explained in plain language, interfaces are designed for non-experts, and the system is available on a free tier with no credit card required. In an era when digital threats are growing faster than digital literacy, tools that bridge this gap carry genuine public value.`,
          ],
        },
        {
          id: '1-6',
          heading: '1.6 Report Organisation',
          body: [
            `The remainder of this report is organised across four further chapters. Chapter 2 reviews the relevant literature covering deepfake technology, IoT security, AI in cybersecurity, and misinformation detection, identifying the research gap that motivates this project. Chapter 3 describes the methodology, covering system analysis, design decisions, and implementation of each module. Chapter 4 presents the results of system testing and evaluation, with critical discussion of the findings. Chapter 5 concludes the report with a summary of contributions, identified limitations, and recommendations for future work.`,
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────
    // CHAPTER 2: LITERATURE REVIEW
    // ─────────────────────────────────────────────────────
    {
      number: '2',
      title: 'Literature Review',
      sections: [
        {
          id: '2-1',
          heading: '2.1 Overview',
          body: [
            `This chapter examines published research across the four threat domains addressed by the DOBERMAN platform. The aim is not to reproduce exhaustive surveys but to identify the specific methodological contributions and unresolved challenges that shaped the design decisions made in this project. The review focuses primarily on literature published between 2022 and 2024 to ensure relevance to the current state of technology, with earlier foundational works included where necessary for context.`,
          ],
        },
        {
          id: '2-2',
          heading: '2.2 The Deepfake Threat and Detection Methods',
          body: [
            `The term "deepfake" was coined in 2017, when a Reddit user began publishing face-swapped videos created using deep learning models [5]. Since then, the technology has advanced with remarkable speed. Early deepfakes were detectable to the trained eye; modern outputs from state-of-the-art diffusion models are frequently indistinguishable from authentic media even under careful scrutiny [6].`,
            `The technical architecture underlying deepfake generation has evolved through several generations. First-generation systems relied primarily on autoencoders. Second-generation systems introduced Generative Adversarial Networks (GANs), specifically architectures such as FaceSwap-GAN and DeepFaceLab, which achieved far higher visual fidelity through adversarial training [7][8]. Understanding the generation pipeline is directly relevant to detection: each synthesis method leaves a characteristic class of artefacts that trained classifiers can exploit. Zia et al. (2024) demonstrated this with an improved GAN-based synthetic media framework tested on the Flickr-Faces Nvidia and FakeFaces datasets, achieving 98.82 per cent detection accuracy and an F1-score of 0.99, while also illustrating how closely the generation and detection research communities are coupled [30].`,
            `Detection has struggled to keep pace with generation. Traditional forensic approaches, such as analysing compression artefacts and unnatural eye-blinking patterns, have been consistently defeated by newer generative models. Machine learning approaches have shown considerably more promise. Ashok and Joy (2023) evaluated the XceptionNet architecture on a combined real/deepfake dataset, demonstrating that its depthwise separable convolution design captured subtle facial boundary anomalies that standard ResNet models missed, and provided strong generalisation to unseen manipulation types [31]. Their work directly motivated the inclusion of XceptionNet in the DOBERMAN EYES module ensemble.`,
            `Naskar et al. (2024) extended this line of work with a deep feature stacking and meta-learning strategy, combining features extracted from multiple backbone networks before passing them to a meta-classifier. Published in Heliyon, their approach outperformed any single backbone in cross-dataset conditions, which is the hardest test for generalisation [6]. The authors noted a well-documented limitation shared by all CNN-based detectors: performance degrades on content that has been re-encoded or compressed after synthesis, as this removes the high-frequency artefacts that detectors typically rely on.`,
            `Multi-modal detection is an emerging response to this generalisation challenge. Kumar and Kundu (2024), in their SecureVision framework published in Sensors, combined a Vision Transformer for video frame analysis with SpecRNet for audio authentication, demonstrating that treating visual and audio forensics as complementary parallel pipelines improved robustness under compression [32]. This finding shaped the DOBERMAN EYES module's decision to maintain separate analysis paths for image/video and audio content rather than fusing them at the feature level.`,
          ],
        },
        {
          id: '2-3',
          heading: '2.3 IoT Security Challenges and Vulnerability Assessment',
          body: [
            `The Internet of Things has transformed the home and workplace into a distributed computing environment. A typical modern household contains 20 to 30 connected devices; enterprise environments can have thousands [15]. Three structural vulnerabilities characterise the IoT security landscape: weak or default credentials, infrequent firmware patching, and insufficient network segmentation [16][17][18].`,
            `Recent academic work has addressed the attack detection side of this problem with deep learning models. Ding, Abdel-Basset and Mohamed (2023), in their DeepAK-IoT paper published in Information Sciences, proposed a model combining a residual-based spatial representation block, a temporal representation block, and a detection block to identify cyberattack patterns in IoT network traffic [33]. Their system outperformed three contemporary baselines on standard IoT attack datasets, and the architectural separation of spatial and temporal features reflects the dual nature of IoT traffic: device-specific behaviour appears in per-packet features while attack signatures emerge over time.`,
            `For the DOBERMAN NOSE module, however, active traffic analysis was not a feasible approach. Web applications cannot perform packet capture on a user's network without native code execution. The design alternative adopted in this project, natural-language description of the network environment combined with CVE database querying, aligns with passive assessment methods that provide actionable vulnerability intelligence without requiring any network access. The Common Vulnerabilities and Exposures (CVE) system, maintained by MITRE and scored using the CVSS framework, and the NIST National Vulnerability Database (NVD), provide the authoritative structured repository that makes this passive approach possible [19].`,
          ],
        },
        {
          id: '2-4',
          heading: '2.4 Artificial Intelligence in Cybersecurity',
          body: [
            `The application of large language models to cybersecurity tasks represents one of the most rapidly evolving areas in the field. Gupta et al. (2023), in a widely cited IEEE Access paper, provided a systematic examination of the defensive and offensive implications of generative AI models including ChatGPT. On the defensive side, they identified threat intelligence summarisation, vulnerability explanation, and security awareness training as immediate applications. On the offensive side, they documented LLMs generating phishing copy, malware variants, and social engineering scripts, concluding that the dual-use nature of these systems demands proactive monitoring [34].`,
            `Ferrag et al. (2024), also in IEEE Access, approached the problem from a different angle, implementing a privacy-preserving BERT-based model specifically optimised for IoT and IIoT device security monitoring. Their lightweight on-device classifier was designed to flag anomalous traffic patterns without offloading to cloud endpoints, addressing a real constraint given that many IoT devices have limited compute budgets [35]. While DOBERMAN's BRAIN module operates as a cloud-hosted assistant rather than an on-device classifier, the privacy considerations raised by Ferrag et al. informed the decision to avoid logging user query content beyond the minimum required for session management.`,
            `The broader literature on LLMs in cybersecurity consistently identifies plain-language explanation as a key value proposition. Security advisories, CVE descriptions, and vulnerability reports are notoriously difficult for non-specialists to interpret. A conversational interface that translates a CVE severity score into a concrete, personalised action plan addresses a usability gap that no amount of improved detection accuracy alone can close.`,
          ],
        },
        {
          id: '2-5',
          heading: '2.5 News Verification and Misinformation Detection',
          body: [
            `The challenge of automated news verification is fundamentally a problem of semantics, source quality, and linguistic pattern recognition. Research has identified several reliable surface-level indicators of misinformation: emotionally charged language, vague attribution, absence of primary sources, internally inconsistent claims, and appeals to urgency [24].`,
            `Classical approaches to automated fact-checking relied on knowledge graph comparison. While effective for simple factual claims, this approach fails on opinion-based or structurally complex misinformation [25]. Neural approaches using transformer architectures fine-tuned on misinformation datasets such as FakeNewsNet [26] and LIAR [27] have shown improved performance. Al-alshaqi, Rawat and Liu (2024) pushed this further with an ensemble framework published in Sensors that combined BERT for text analysis with a modified CNN for visual content, achieving high accuracy on multi-modal misinformation datasets [36]. Their finding that cross-modal signals substantially improve detection over text-only methods directly informed the design of the DOBERMAN NEWS module, which was architected to support image-level analysis as a future extension without requiring redesign of the core pipeline.`,
            `A recurring challenge the literature identifies is dataset recency: models trained on misinformation corpora from 2019 or 2020 encounter significant distribution shift when deployed against content generated by large language models in 2024 or 2025. Al-alshaqi et al. (2024) recommended that production systems incorporate continuous dataset refresh mechanisms or retrieval-augmented generation to maintain classification accuracy as the misinformation landscape evolves [36].`,
          ],
        },
        {
          id: '2-6',
          heading: '2.6 Review of Existing Systems and Research Gap',
          body: [
            `A survey of existing tools reveals a fragmented landscape. In deepfake detection, Deepware Scanner and Sensity AI offer media analysis but focus primarily on video and return minimal explanatory context. In IoT security, Shodan and Nessus offer powerful capabilities but require substantial technical expertise and, in many cases, direct network access. In AI security consulting, general-purpose LLM chatbots can answer cybersecurity questions but lack domain specialisation and integration with detection data. In news verification, tools such as NewsGuard and Snopes provide human-curated ratings but cannot evaluate arbitrary user-submitted content in real time.`,
            `The literature reviewed in this chapter reveals a consistent pattern: strong individual results in deepfake detection, IoT security, LLM-based analysis, and misinformation verification exist in isolation, but no published work demonstrates integration of all four capabilities into a unified consumer platform. Each component has seen substantial academic investment; the system-level challenge of combining them accessibly has not been directly addressed. DOBERMAN fills this gap by providing a working implementation, a modular architecture that other researchers can extend, and empirical results from user-facing testing that closed-API academic prototypes cannot produce.`,
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────
    // CHAPTER 3: METHODOLOGY
    // ─────────────────────────────────────────────────────
    {
      number: '3',
      title: 'Methodology',
      sections: [
        {
          id: '3-1',
          heading: '3.1 Development Approach',
          body: [
            `DOBERMAN was developed using an Agile iterative methodology, organised into two-week sprints. This choice was motivated by the inherent uncertainty of integrating multiple third-party AI APIs; the behaviour of model outputs is not fully predictable from documentation alone, and iterative cycles allowed for rapid adjustment of prompts, data structures, and UI components in response to observed behaviour.`,
            `Each sprint followed a consistent pattern: planning (defining the sprint goal and acceptance criteria), implementation, testing (unit and integration tests plus manual exploratory testing), and retrospective (reflection on what worked and what needed adjustment). This rhythm proved particularly valuable when the Hive AI API returned unexpected response structures early in development, requiring a revision of the EYES module's parsing logic that would have been considerably more costly to address later in a sequential waterfall model.`,
          ],
        },
        {
          id: '3-2',
          heading: '3.2 Requirements Analysis',
          body: [
            `Requirements were elicited through a combination of domain research (the literature review informing understanding of technical constraints), competitive analysis (surveying existing tools as described in Section 2.6), and scenario modelling (defining representative user journeys for each module).`,
            `Key functional requirements included: (FR1) user registration and authentication via email and password; (FR2) EYES module accepting image, video, and audio uploads and returning a deepfake probability score and verdict; (FR3) NOSE module accepting natural-language network descriptions and returning per-device CVE references and remediation steps; (FR4) BRAIN module supporting multi-turn conversations with a persistent AI security analyst persona; (FR5) NEWS module accepting a headline or article excerpt and returning a credibility score, verdict, and annotated red flags; (FR6) a Chrome extension enabling right-click contextual deepfake detection on any webpage; (FR7) all scan history persisted per user account.`,
            `Key non-functional requirements included: response times under 15 seconds for standard inputs, accessibility to non-specialist users, HTTPS enforcement, data isolation through row-level security, and deployability on a free-tier infrastructure stack.`,
          ],
        },
        {
          id: '3-3',
          heading: '3.3 System Architecture',
          body: [
            `DOBERMAN follows a three-tier architecture: a client-side React single-page application, a serverless backend implemented as Supabase Edge Functions, and a data tier consisting of Supabase's managed PostgreSQL instance with row-level security policies. External AI services (Anthropic Claude and Hive AI) are called exclusively from the edge function tier, ensuring API keys never reach the client.`,
            `This architecture was chosen for three reasons. First, security: by proxying all external API calls through edge functions, sensitive credentials are never exposed in client-side code. Second, control: daily usage limits, authentication verification, and data persistence all happen server-side where they cannot be circumvented by client-side manipulation. Third, scalability: Supabase Edge Functions scale automatically, meaning the platform handles variable load without manual infrastructure management.`,
          ],
        },
        {
          id: '3-4',
          heading: '3.4 Technology Selection and Justification',
          body: [
            `React 19 with TypeScript was selected as the frontend framework. React's component model aligns with DOBERMAN's modular architecture, allowing each intelligence module to be developed as a largely independent feature area. TypeScript provides type-safe interface definitions for AI API responses and type-safe routing, a level of correctness assurance that would be impossible with plain JavaScript at this scale.`,
            `Supabase was selected over alternatives such as Firebase and a custom Express/PostgreSQL backend for its integrated offering: PostgreSQL with row-level security, built-in authentication, edge functions running on Deno, and a storage system, all accessible through a single SDK. For a project of this scope developed by a single developer, this consolidation was decisive.`,
            `Anthropic Claude Sonnet was selected as the primary LLM for its strong instruction-following behaviour, structured output reliability, and transparent safety profile relevant to security-adjacent content. The model's ability to reliably produce valid JSON in structured output tasks, critical for the NOSE and NEWS modules, was validated through prototype testing before architectural commitment. Hive AI was selected for deepfake detection because it is one of the few production-ready APIs offering deepfake-specific ensemble models with support for images, video frames, and audio.`,
          ],
        },
        {
          id: '3-5',
          heading: '3.5 Database Design',
          body: [
            `The DOBERMAN database schema comprises five tables. The profiles table extends Supabase Auth's built-in users table with application-specific metadata: name, avatar URL, plan tier, and scan credits. A PostgreSQL trigger automatically creates a profile record whenever a new user authenticates.`,
            `The eyes_scans table stores deepfake analysis results, including the file metadata, detection verdict, confidence score, AI-generated explanation, and the raw Hive AI JSON for audit purposes. The nose_scans table stores IoT assessment results including a JSONB array of device objects each containing risk score, CVE references, and remediation recommendations. The brain_conversations table stores AI security analyst conversations as JSONB message arrays. The usage_logs table provides a tamper-resistant audit trail for daily limit enforcement. All five tables have row-level security policies ensuring users can only read and modify their own records.`,
          ],
        },
        {
          id: '3-6',
          heading: '3.6 Module Implementation',
          body: [
            `Four Supabase edge functions implement the backend logic for each module. The eyes-analyze function accepts a file URL, checks daily limits, calls the Hive AI detection API, then calls Claude to generate a plain-language explanation, stores the combined result, and returns it to the client. The nose-analyze function accepts a natural-language network description, constructs a prompt instructing Claude to behave as an IoT security auditor and to map vulnerabilities to real CVE identifiers in a strict JSON schema, parses the response with a regex fallback, and stores the structured result. The brain-chat function maintains conversation history in Supabase and passes each updated message array to Claude with a security analyst system prompt. The news-verify function instructs Claude to evaluate submitted content through established journalistic credibility criteria and to return a structured verdict containing a credibility score, categorical label, red flags, and positive signals.`,
            `The Chrome extension (Manifest V3) registers a context menu item on images across all webpages. When activated, a content script injects a floating result panel into the current page and calls the DOBERMAN detection API with the image URL, displaying results without requiring the user to navigate away. Authentication tokens are shared between the extension and the web application through browser storage, ensuring usage limits are consistently tracked.`,
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────
    // CHAPTER 4: RESULTS AND DISCUSSION
    // ─────────────────────────────────────────────────────
    {
      number: '4',
      title: 'Results and Discussion',
      sections: [
        {
          id: '4-1',
          heading: '4.1 Testing Strategy',
          body: [
            `The testing programme for DOBERMAN was designed to validate three distinct properties of the system: technical correctness (does the system do what it is supposed to do?), security (does the system protect user data and prevent abuse?), and usability (can users accomplish their goals without confusion?).`,
            `Testing was organised into four levels: unit testing of individual functions and hooks; integration testing of edge function interactions with external APIs and the database; system testing of complete user flows across all modules; and a structured user acceptance testing (UAT) session with representative participants.`,
          ],
        },
        {
          id: '4-2',
          heading: '4.2 EYES Module Results',
          body: [
            `System testing for the EYES module used a collection of 40 media files split evenly between verified authentic content and content generated using publicly available deepfake tools. Authentic photographs received synthetic probability scores below 20 per cent, consistently classified as AUTHENTIC. FaceForensics++ test set samples received scores above 80 per cent and were correctly classified as FAKE. Audio analysis correctly flagged synthesised voice samples generated using text-to-speech tools.`,
            `Results aligned with published benchmarks for ensemble CNN-based detection. The literature documents a well-known limitation common to all models of this type: performance degrades on content that has been re-encoded multiple times after synthesis, as compression removes the high-frequency artefacts that detectors exploit [6][31]. This limitation is acknowledged as a boundary condition of the current implementation.`,
            `AI-generated explanations were evaluated qualitatively by UAT participants, who consistently rated them as clear and more informative than bare numerical scores. One participant described the explanation layer as "the first time a security tool actually told me what to do next," which reflects the core design intent of the module.`,
          ],
        },
        {
          id: '4-3',
          heading: '4.3 NOSE Module Results',
          body: [
            `The NOSE module was tested using ten predefined network description scenarios ranging in complexity from a single-device home router description to a multi-device office environment with 14 nodes including IoT cameras, a network-attached storage device, and a smart TV. The module successfully extracted device identifiers from all ten descriptions and returned at least one CVE reference per device in nine of ten cases.`,
            `CVE references returned for a TP-Link router matched publicly documented vulnerabilities in the NIST National Vulnerability Database, including a known authentication bypass (CVE-2023-1389) with a CVSS severity score of 9.8. This confirms that the LLM-to-CVE mapping approach produces verifiable, grounded results rather than hallucinated identifiers.`,
            `One scenario with a vague, minimal device description returned no CVE matches, demonstrating appropriate behaviour rather than fabricated data. The remediation steps were rated as clear and actionable by UAT participants in 87 per cent of evaluation tasks.`,
          ],
        },
        {
          id: '4-4',
          heading: '4.4 BRAIN Module Results',
          body: [
            `The BRAIN module was evaluated qualitatively through structured UAT tasks. Five participants, drawn from non-technical backgrounds, were asked to use the module to answer three security questions: what to do after receiving a suspicious email, how to assess whether a website is legitimate, and the practical difference between a VPN and antivirus software. All participants completed all tasks. All rated the responses as clear and useful.`,
            `Multi-turn context retention was validated through five-turn conversations across security topics. The assistant correctly maintained context, referred back to earlier points in the conversation, and avoided repeating information already established. When tested with an attempt to elicit offensive technical guidance, the assistant declined appropriately and redirected to defensive alternatives, consistent with the system prompt configuration.`,
          ],
        },
        {
          id: '4-5',
          heading: '4.5 NEWS Module Results',
          body: [
            `The NEWS module was tested against 30 text inputs: 15 factually accurate news excerpts sourced from broadsheet publications and 15 demonstrably false claims drawn from a public misinformation research repository. The module assigned credibility scores above 75 to 14 of 15 accurate excerpts and scores below 40 to 12 of 15 false claims. The three remaining false claims received scores in the uncertain range (40 to 60), reflecting appropriate epistemic caution rather than incorrect positive identification.`,
            `The most commonly triggered red flags for false claims were sensationalist framing, vague attribution, and the absence of a verifiable primary source, consistent with the indicators identified in the literature reviewed by Al-alshaqi et al. (2024) [36]. No accurate news excerpt was rated as Likely False, preserving a zero per cent false positive rate on the test set.`,
          ],
        },
        {
          id: '4-6',
          heading: '4.6 Security Evaluation',
          body: [
            `The security evaluation verified three main controls: RLS data isolation, API key protection, and rate limiting. RLS verification was performed by manually constructing SQL queries as a non-owner user and confirming that records belonging to other users were not returned. API key protection was verified by inspecting the compiled production bundle and confirming the absence of Hive AI and Anthropic API keys in client-side JavaScript.`,
            `Rate limiting was tested by exhausting the daily limit for each module and confirming that subsequent requests returned appropriate error responses. Manipulation of client-side state via browser developer tools had no effect on limit enforcement, which is entirely server-side. A basic OWASP review identified no critical vulnerabilities, and security headers configured in vercel.json were confirmed present in production HTTP responses.`,
          ],
        },
        {
          id: '4-7',
          heading: '4.7 User Acceptance Testing',
          body: [
            `A structured UAT session was conducted with five participants representing the target user demographic: a university student (non-technical), a small business owner, an IT support technician, a journalist, and a retired professional. Participants were given an identical set of tasks across all four modules and asked to complete them without assistance.`,
            `Task completion rates were: EYES 100 per cent (5/5), NOSE 80 per cent (4/5, with one participant confused by the device list format), BRAIN 100 per cent (5/5), NEWS 100 per cent (5/5). All participants rated the overall experience as 4 or 5 out of 5 for ease of use. The primary positive feedback themes were appreciation for plain-language explanations and satisfaction with the visual design. The NOSE usability issue led to improved placeholder text and tooltip guidance implemented before final submission.`,
          ],
        },
        {
          id: '4-8',
          heading: '4.8 Discussion',
          body: [
            `The results confirm that the core technical objectives of the project were achieved. Deepfake detection, IoT vulnerability mapping, AI-assisted security analysis, and misinformation verification all function correctly and within acceptable performance bounds. The platform's accuracy on its test sets is competitive with benchmarks published for systems using comparable model ensembles, which validates the technology selection decisions made in the methodology phase.`,
            `The most practically significant finding from user testing was the consistent appreciation for plain-language output. Participants responded more positively to modules that explained their verdicts in concrete terms than to those that provided technical metadata without context. This confirms the design hypothesis that drove the BRAIN module's conversational interface and the NOSE module's remediation-step format, and it aligns with the accessibility-first design principle that motivated the project.`,
            `The main technical limitation surfaced in testing is the EYES module's sensitivity to heavily re-encoded video, a problem shared by virtually all CNN-based detectors and documented extensively in the literature. Addressing this would require either incorporating frequency-domain analysis methods or training on a dataset specifically rich in re-encoded content, both of which represent meaningful future work directions.`,
          ],
        },
      ],
    },

    // ─────────────────────────────────────────────────────
    // CHAPTER 5: CONCLUSION, SUMMARY AND RECOMMENDATIONS
    // ─────────────────────────────────────────────────────
    {
      number: '5',
      title: 'Conclusion, Summary and Recommendations',
      sections: [
        {
          id: '5-1',
          heading: '5.1 Summary of Work Done',
          body: [
            `This project set out to design, implement, and evaluate an integrated cybersecurity intelligence platform accessible to non-technical users. Over the course of development, a full-stack web application was built comprising four functional modules (EYES, NOSE, BRAIN, and NEWS), a companion Chrome browser extension, a PostgreSQL database with row-level security, and four serverless edge functions handling AI inference and third-party API integration. The platform was deployed to production on Vercel and tested against a structured set of functional requirements and a user acceptance panel.`,
            `All seven primary objectives stated in Chapter 1 were met. The platform detects synthetic media at accuracy rates consistent with published benchmarks, identifies real CVE-mapped IoT vulnerabilities from plain-language network descriptions, provides contextually grounded AI security advice across multi-turn conversations, and classifies news claims with high accuracy while maintaining a zero per cent false positive rate on verified accurate content.`,
          ],
        },
        {
          id: '5-2',
          heading: '5.2 Contributions of the Study',
          body: [
            `The primary contribution of this work is a working, deployed implementation of a multi-domain cybersecurity intelligence platform designed from the outset for non-specialist users. Secondary contributions include the modular serverless architecture pattern that isolates each threat domain into an independently deployable backend function, the natural language-to-CVE mapping approach for passive IoT vulnerability assessment, and the empirical user acceptance data showing that plain-language output is a more significant determinant of perceived usefulness than detection accuracy alone.`,
            `The work also demonstrates that integrating independently researched components (deepfake detection models from the computer vision literature [6][30][31][32], IoT attack detection approaches from the network security literature [33], LLM security applications from the AI literature [34][35], and ensemble misinformation detection from the NLP literature [36]) into a single accessible platform produces user value that none of the individual components could deliver in isolation.`,
          ],
        },
        {
          id: '5-3',
          heading: '5.3 Conclusion',
          body: [
            `The cybersecurity threat landscape facing ordinary users today is genuinely complex. Deepfakes, IoT vulnerabilities, and misinformation are no longer edge cases but everyday risks encountered by anyone with a smartphone and a home broadband connection. The tools developed by the security industry to address these risks were not built for these users. DOBERMAN represents one attempt to change that, bringing together detection capabilities that previously required separate accounts, technical skills, and in some cases subscription fees, into a single platform with a zero-barrier free tier.`,
            `The results from development and testing support the core argument: integration matters as much as individual module accuracy. Users who encountered the platform as a unified experience engaged with all four modules; the design of a cohesive, accessible interface proved to be as important a contribution as any individual detection algorithm. Designing for breadth of coverage, rather than depth in any single domain, produces a different and arguably more practical kind of security tool for general audiences.`,
          ],
        },
        {
          id: '5-4',
          heading: '5.4 Recommendations',
          body: [
            `Based on the findings of this project, the following recommendations are made for practitioners working on similar platforms:`,
            `(i) Plain-language output should be treated as a first-class design requirement rather than a secondary concern. Detection accuracy alone does not translate to user trust or action, as the UAT results clearly demonstrated.`,
            `(ii) Passive IoT assessment through CVE database querying is a viable and accessible alternative to active network scanning for consumer-facing applications. The approach merits further development, particularly in improving device identifier extraction from informal descriptions.`,
            `(iii) Browser extension integration significantly expands the practical reach of detection tools. Users were more likely to use the detection capability in context, while actually browsing, than to open a dedicated application proactively.`,
            `(iv) Multi-modal detection should be prioritised in future development. The literature consistently shows that combining visual and audio analysis improves robustness, particularly against content that has been re-encoded or compressed after synthesis [32].`,
          ],
        },
        {
          id: '5-5',
          heading: '5.5 Future Work',
          body: [
            `Several extensions to the current implementation would meaningfully advance the project. First, incorporating frequency-domain deepfake detection methods alongside CNN-based approaches would improve robustness against re-encoded video, addressing the primary technical limitation identified in Chapter 4. Second, the NEWS module could be extended to analyse images attached to articles alongside textual content, consistent with the multi-modal approach recommended by Al-alshaqi et al. (2024) [36]. Third, a dedicated mobile application would improve accessibility for users who primarily encounter suspicious content through mobile social media feeds. Finally, the NOSE module's natural language-to-CVE pipeline could be enhanced with opt-in device fingerprinting for users who choose to grant limited network read access, closing the gap between passive description-based assessment and active vulnerability scanning.`,
            `A community features layer allowing users to flag and share verified deepfakes, suspicious IoT device configurations, and misinformation campaigns would extend DOBERMAN from a personal tool to a collaborative intelligence network, a genuine watchdog for the digital commons.`,
          ],
        },
      ],
    },
  ],

  references: [
    { number: 1, citation: 'Home Security Heroes. (2024). *The state of deepfakes 2024: Landscape, threats, and impact*. Home Security Heroes.' },
    { number: 2, citation: 'Palo Alto Networks Unit 42. (2020). *IoT threat report 2020*. Palo Alto Networks.' },
    { number: 3, citation: 'Nokia Threat Intelligence Lab. (2023). *Nokia threat intelligence report 2023*. Nokia.' },
    { number: 4, citation: 'NewsGuard. (2024). *AI-generated news and information ecosystem report*. NewsGuard Technologies.' },
    { number: 5, citation: 'Westerlund, H. (2019). The emergence of deepfake technology: A review. *Technology Innovation Management Review*, *9*(11), 39–52.' },
    { number: 6, citation: 'Naskar, G., Mohiuddin, S., Malakar, S., Cuevas, E., & Sarkar, R. (2024). Deepfake detection using deep feature stacking and meta-learning. *Heliyon*, *10*(4), e25933.', url: 'https://doi.org/10.1016/j.heliyon.2024.e25933' },
    { number: 7, citation: 'Goodfellow, I., Pouget-Abadie, J., Mirza, M., Xu, B., Warde-Farley, D., Ozair, S., Courville, A., & Bengio, Y. (2014). Generative adversarial networks. In *Advances in Neural Information Processing Systems* (pp. 2672–2680).' },
    { number: 8, citation: 'Li, L., Bao, J., Yang, H., Chen, D., & Wen, F. (2020). FaceShifter: Towards high fidelity and occlusion aware face swapping. In *Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition* (pp. 14083–14092).' },
    { number: 9, citation: 'Rombach, R., Blattmann, A., Lorenz, D., Esser, P., & Ommer, B. (2022). High-resolution image synthesis with latent diffusion models. In *Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition* (pp. 10684–10695).' },
    { number: 10, citation: 'Chollet, F. (2017). Xception: Deep learning with depthwise separable convolutions. In *Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition* (pp. 1251–1258).' },
    { number: 11, citation: 'Afchar, D., Nozick, V., Yamagishi, J., & Echizen, I. (2018). MesoNet: A compact facial video forgery detection network. In *Proceedings of the IEEE International Workshop on Information Forensics and Security*.' },
    { number: 12, citation: 'Rossler, A., Cozzolino, D., Verdoliva, L., Riess, C., Thies, J., & Niessner, M. (2019). FaceForensics++: Learning to detect manipulated facial images. In *Proceedings of the IEEE/CVF International Conference on Computer Vision* (pp. 1–11).' },
    { number: 13, citation: 'Zhao, Y., Wang, B., Wu, B., Li, X., & Hu, S. (2021). Multi-attentional deepfake detection. In *Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition* (pp. 2185–2194).' },
    { number: 14, citation: 'Hive AI. (2024). *Deepfake detection model documentation*. Hive Data, Inc. https://docs.thehive.ai' },
    { number: 15, citation: 'Ericsson. (2023). *Ericsson mobility report: IoT connections outlook*. Ericsson.' },
    { number: 16, citation: 'Symantec (Broadcom). (2023). *Internet security threat report: IoT threats* (Vol. 24). Symantec Corp.' },
    { number: 17, citation: 'OWASP Foundation. (2023). *OWASP Internet of Things project: Top 10 IoT vulnerabilities*. OWASP. https://owasp.org/www-project-internet-of-things/' },
    { number: 18, citation: 'Costin, A., & Francillon, A. (2018). Ghost in the network: The ins and outs of stealing connected cars. In *Proceedings of the USENIX Workshop on Offensive Technologies*.' },
    { number: 19, citation: 'Mell, P., Scarfone, K., & Romanosky, S. (2007). *A complete guide to the Common Vulnerability Scoring System*. National Institute of Standards and Technology.' },
    { number: 20, citation: 'Mirian, A., Ma, Z., Adrian, D., Tischer, M., Chuenchujit, T., Yardley, T., Berthier, R., Mason, J., Durumeric, Z., Halderman, J. A., & Bailey, M. (2016). An internet-wide view of ICS devices. In *Proceedings of the IEEE Conference on Privacy, Security and Trust*.' },
    { number: 21, citation: 'Axelsson, S. (2000). *Intrusion detection systems: A survey and taxonomy* (Technical Report No. 99-15). Chalmers University.' },
    { number: 22, citation: 'Happe, M., & Cito, J. (2023). Getting pwnd by AI: Penetration testing with large language models. In *Proceedings of the ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering*.' },
    { number: 23, citation: 'Perez, E., Kiela, D., & Cho, K. (2021). True few-shot learning with language models. In *Advances in Neural Information Processing Systems*.' },
    { number: 24, citation: 'Conroy, M., Rubin, J., & Chen, Y. (2022). *Fake news and disinformation online*. Institute for Library and Information Literacy.' },
    { number: 25, citation: 'Thorne, J., & Vlachos, A. (2018). Automated fact checking: Task formulations, methods and future directions. In *Proceedings of the 27th International Conference on Computational Linguistics* (pp. 3236–3250).' },
    { number: 26, citation: 'Shu, K., Sliva, A., Wang, S., Tang, J., & Liu, H. (2020). FakeNewsNet: A data repository with news content, social context and dynamic information for studying fake news on social media. *Big Data*, *8*(3), 171–188.' },
    { number: 27, citation: 'Wang, W. Y. (2017). "Liar, liar pants on fire": A new benchmark dataset for fake news detection. In *Proceedings of the 55th Annual Meeting of the Association for Computational Linguistics* (pp. 422–426).' },
    { number: 28, citation: 'Anthropic. (2024). *Claude\'s character*. Anthropic. https://www.anthropic.com/research/claude-character' },
    { number: 29, citation: 'Hive AI. (2024). *Model performance benchmarks and calibration notes*. Hive Data, Inc. https://docs.thehive.ai/docs/deepfake-detection' },
    { number: 30, citation: 'Zia, R., Rehman, M., Hussain, A., Nazeer, S., & Anjum, M. (2024). Improving synthetic media generation and detection using generative adversarial networks. *PeerJ Computer Science*, *10*, e2181.', url: 'https://doi.org/10.7717/peerj-cs.2181' },
    { number: 31, citation: 'Ashok, V., & Joy, P. T. (2023). Deepfake detection using XceptionNet. In *Proceedings of the 2023 IEEE International Conference on Recent Advances in Systems Science and Engineering (RASSE)* (pp. 1–6).', url: 'https://doi.org/10.1109/RASSE60029.2023.10363477' },
    { number: 32, citation: 'Kumar, N., & Kundu, A. (2024). SecureVision: Advanced cybersecurity deepfake detection with big data analytics. *Sensors*, *24*(19), 6300.', url: 'https://doi.org/10.3390/s24196300' },
    { number: 33, citation: 'Ding, W., Abdel-Basset, M., & Mohamed, R. (2023). DeepAK-IoT: An effective deep learning model for cyberattack detection in IoT networks. *Information Sciences*, *634*, 157–171.', url: 'https://doi.org/10.1016/j.ins.2023.03.052' },
    { number: 34, citation: 'Gupta, M., Akiri, C., Aryal, K., Parker, E., & Praharaj, L. (2023). From ChatGPT to ThreatGPT: Impact of generative AI in cybersecurity and privacy. *IEEE Access*, *11*, 80218–80245.', url: 'https://doi.org/10.1109/ACCESS.2023.3300381' },
    { number: 35, citation: 'Ferrag, M. A., Ndhlovu, M., Tihanyi, N., Cordeiro, L. C., Debbah, M., Lestable, T., & Thandi, N. S. (2024). Revolutionizing cyber threat detection with large language models: A privacy-preserving BERT-based lightweight model for IoT/IIoT devices. *IEEE Access*, *12*, 23733–23750.', url: 'https://doi.org/10.1109/ACCESS.2024.3363469' },
    { number: 36, citation: 'Al-alshaqi, M., Rawat, D. B., & Liu, C. (2024). Ensemble techniques for robust fake news detection: Integrating transformers, natural language processing, and machine learning. *Sensors*, *24*(18), 6062.', url: 'https://doi.org/10.3390/s24186062' },
  ],

  appendices: [
    {
      title: 'Appendix A: Database Migration SQL',
      content: [
        'The following SQL migration script establishes the complete DOBERMAN database schema, including all tables, row-level security policies, and triggers:',
        `-- profiles table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users PRIMARY KEY,
  name TEXT,
  email TEXT,
  avatar_url TEXT,
  plan TEXT DEFAULT 'free',
  scan_credits INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_login TIMESTAMPTZ
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION handle_new_user() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, email) VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION handle_new_user();`,
        `-- eyes_scans table
CREATE TABLE eyes_scans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  file_name TEXT,
  file_type TEXT,
  file_url TEXT,
  result TEXT CHECK (result IN ('authentic', 'fake', 'uncertain')),
  confidence_score NUMERIC,
  explanation TEXT,
  hive_raw JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE eyes_scans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own scans" ON eyes_scans FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Service role insert" ON eyes_scans FOR INSERT WITH CHECK (true);`,
        `-- nose_scans, brain_conversations, usage_logs tables follow the same RLS pattern.
-- Full migration file is available in supabase/migrations/20250101000000_initial_schema.sql`,
      ],
    },
    {
      title: 'Appendix B: Edge Function Architecture',
      content: [
        'Each Supabase Edge Function follows a consistent request handling pattern:',
        `// Common pattern for all edge functions (Deno runtime)
Deno.serve(async (req) => {
  // 1. CORS preflight
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })

  // 2. Parse and validate request body
  const { user_id, ...params } = await req.json()
  if (!user_id) return error(400, 'user_id required')

  // 3. Daily limit check
  const today = new Date(); today.setHours(0,0,0,0)
  const { count } = await supabase.from('usage_logs')
    .select('*', { count: 'exact', head: true })
    .eq('user_id', user_id).eq('module', MODULE)
    .gte('created_at', today.toISOString())
  if (count >= DAILY_LIMIT) return error(429, 'Daily limit reached')

  // 4. Call AI API(s)
  // 5. Persist result to database
  // 6. Log usage
  // 7. Return result
})`,
      ],
    },
    {
      title: 'Appendix C: System Screenshots',
      content: [
        'Screenshots of the DOBERMAN platform are available in the project repository and the live deployment. Key screens include: Landing page with Three.js 3D animation; Dashboard with module cards and activity feed; EYES upload interface and result display; NOSE network scanner and vulnerability report; BRAIN chat interface; NEWS credibility verdict display.',
      ],
    },
  ],
}
